import { useState } from 'react'
import { fireEvent, render, screen, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { afterEach, describe, expect, test, vi } from 'vitest'
import { BannerTemplateEditor, defaultBannerDraft } from './BannerTemplateEditor.jsx'
import { studioTemplates } from '../../shared/studioTemplates.js'

function Harness({ api, initial = {} }) {
  const [draft, setDraft] = useState(() => ({ ...defaultBannerDraft(), ...initial }))
  const manifest = studioTemplates.find(item => item.id === 'bold-announcement')
  return <BannerTemplateEditor template={{ id: manifest.id, version: manifest.version, name: manifest.name, manifest }}
    draft={draft} onChange={setDraft} onBack={() => {}} onCreateCampaign={() => {}} api={api} />
}
afterEach(() => vi.restoreAllMocks())

describe('template content and output selection', () => {
  test('labels template editor as draft-only and disables disconnected actions', () => {
    render(<Harness initial={{ imageSource: 'upload', imageName: 'synthetic.png' }} />)
    expect(screen.getByText('Template preview — not a saved campaign')).toBeVisible()
    expect(screen.getByRole('button', { name: 'Send to Figma for review' })).toBeDisabled()
    expect(screen.getByRole('button', { name: 'Generate image' })).toBeDisabled()
    expect(screen.getByRole('button', { name: 'Convert to video' })).toBeDisabled()
    expect(screen.getByText('Create a campaign to generate and review banners.')).toBeVisible()
  })

  test('preserves oversized pasted copy and blocks outputs with an actionable error', async () => {
    const user = userEvent.setup()
    render(<Harness />)
    const headline = screen.getByRole('textbox', { name: 'Headline' })
    await user.click(headline)
    await user.clear(headline)
    const text = 'Long campaign headline '.repeat(8)
    await user.paste(text)
    expect(headline).toHaveValue(text)
    expect(headline).toHaveAttribute('aria-invalid', 'true')
    expect(screen.getByRole('alert')).toHaveTextContent('Headline must be at most 80 characters.')
    expect(screen.getByRole('button', { name: 'Download' })).toBeDisabled()
  })
  test('edits alongside a single preview and retains copy when cycling proportions', async () => {
    const user = userEvent.setup()
    const { container } = render(<Harness />)
    expect(screen.getByRole('tab', { name: 'Content', selected: true })).toBeVisible()
    const headline = screen.getByRole('textbox', { name: 'Headline' })
    expect(headline.closest('svg')).toBeNull()
    await user.clear(headline)
    await user.type(headline, 'Shared campaign copy')
    await user.click(screen.getByRole('button', { name: 'Next proportion' }))
    expect(container.querySelector('svg.studio-banner')).toHaveAttribute('data-ratio', 'portrait')
    expect(screen.getByRole('textbox', { name: 'Headline' })).toHaveValue('Shared campaign copy')
    expect(container.querySelectorAll('svg.studio-banner')).toHaveLength(1)
    expect(screen.getByText('1 format selected')).toBeVisible()
    await user.click(screen.getByRole('button', { name: 'Previous proportion' }))
    expect(container.querySelector('svg.studio-banner')).toHaveAttribute('data-ratio', 'square')
    await user.click(screen.getByRole('tab', { name: 'Formats' }))
    await user.click(screen.getByRole('tab', { name: 'Content' }))
    expect(screen.getByRole('textbox', { name: 'Headline' })).toHaveValue('Shared campaign copy')
  })
  test('Google completes its group without hiding or replacing other formats', () => {
    render(<Harness />)
    fireEvent.mouseDown(screen.getByRole('tab', { name: 'Formats' }))
    fireEvent.click(screen.getByRole('checkbox', { name: 'Google' }))
    expect(screen.getByRole('button', { name: 'Download · 4' })).toBeEnabled()
    expect(screen.getByRole('button', { name: 'Deselect Square post · 1080 × 1080' })).toBeVisible()
    expect(screen.getByRole('button', { name: 'Deselect Landscape ad · 1200 × 628' })).toBeVisible()
    expect(screen.getByRole('button', { name: 'Select Portrait post · 1080 × 1350' })).toBeVisible()
    expect(screen.getByRole('checkbox', { name: 'Google' })).toBeChecked()
    expect(screen.getByRole('checkbox', { name: 'Meta' })).toBePartiallyChecked()
    fireEvent.click(screen.getByRole('checkbox', { name: 'Google' }))
    expect(screen.getByText('1 format selected')).toBeVisible()
    expect(screen.getByRole('button', { name: 'Deselect Square post · 1080 × 1080' })).toBeVisible()
    expect(screen.getByRole('checkbox', { name: 'Google' })).not.toBeChecked()
  })
  test('individual changes recalculate overlap and mixed-group clicks complete selection', () => {
    render(<Harness />)
    fireEvent.mouseDown(screen.getByRole('tab', { name: 'Formats' }))
    fireEvent.click(screen.getByRole('button', { name: 'Select Landscape ad · 1200 × 628' }))
    expect(screen.getByRole('checkbox', { name: 'Google' })).toBePartiallyChecked()
    fireEvent.click(screen.getByRole('checkbox', { name: 'Google' }))
    expect(screen.getByText('4 formats selected')).toBeVisible()
    fireEvent.click(screen.getByRole('checkbox', { name: 'Video' }))
    expect(screen.getByText('5 formats selected')).toBeVisible()
    expect(screen.getByRole('checkbox', { name: 'TikTok' })).toBeChecked()
    fireEvent.click(screen.getByRole('checkbox', { name: 'Google' }))
    expect(screen.getByText('2 formats selected')).toBeVisible()
    expect(screen.getByRole('checkbox', { name: 'Video' })).toBePartiallyChecked()
    expect(within(screen.getByRole('tabpanel', { name: 'Formats' })).getAllByRole('button', { name: /^(Select|Deselect) / })).toHaveLength(7)
  })
  test('zero outputs retains editable preview without the redundant footer', () => {
    render(<Harness initial={{ ratioIds: [] }} />)
    expect(screen.getByRole('textbox', { name: 'Caption' })).toHaveValue('')
    expect(screen.getByRole('textbox', { name: 'CTA' })).toBeVisible()
    expect(screen.getByRole('button', { name: 'Download' })).toBeDisabled()
    expect(screen.getByRole('button', { name: 'Send to Figma for review' })).toBeDisabled()
    expect(screen.queryByText('Select at least one format.')).not.toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Next proportion' }))
    expect(screen.getByText('0 formats selected')).toBeVisible()
  })
  test('exports selected output IDs and latest copy rather than the preview ratio', async () => {
    const exportBannerDraft = vi.fn().mockResolvedValue(new Blob(['zip']))
    vi.spyOn(URL, 'createObjectURL').mockReturnValue('blob:test')
    vi.spyOn(URL, 'revokeObjectURL').mockImplementation(() => {})
    vi.spyOn(HTMLAnchorElement.prototype, 'click').mockImplementation(() => {})
    const user = userEvent.setup()
    render(<Harness api={{ exportBannerDraft }} initial={{ imageUrl: 'data:image/png;base64,YWJjZA==' }} />)
    fireEvent.change(screen.getByRole('textbox', { name: 'Headline' }), { target: { value: 'Latest copy' } })
    await user.click(screen.getByRole('button', { name: 'Next proportion' }))
    await user.click(screen.getByRole('button', { name: 'Download' }))
    expect(exportBannerDraft).toHaveBeenCalledWith(expect.objectContaining({ ratioIds: ['square'], values: expect.objectContaining({ headline: 'Latest copy' }) }))
    expect(await screen.findByRole('status')).toHaveTextContent('Downloaded 1 PNG draft.')
  })
})
