import { fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import { beforeEach, describe, expect, test, vi } from 'vitest'
import { TemplateLibrary } from './TemplateLibrary.jsx'
import { createMsdPresentationTemplates } from '../../shared/msdPresentationTemplates.js'
import { studioTemplates } from '../../shared/studioTemplates.js'

beforeEach(() => {
  window.history.replaceState({}, '', '/mvp/templates?category=presentations#presentation-templates')
  localStorage.clear()
  Object.defineProperty(document, 'fonts', { configurable: true, value: { load: () => Promise.resolve([]) } })
  vi.spyOn(HTMLCanvasElement.prototype, 'getContext').mockReturnValue({ font: '', measureText: value => ({ width: value.length * 7 }) })
  Element.prototype.scrollIntoView = vi.fn()
})
describe('presentation template library', () => {
  test('uses only top-level group tabs and restores group selection from the URL', () => {
    window.history.replaceState({}, '', '/mvp/templates?category=web')
    render(<TemplateLibrary templates={[]} onChoose={vi.fn()} />)
    const tabs=within(screen.getByRole('tablist', { name: 'Template categories' })).getAllByRole('tab')
    expect(tabs.map(tab => tab.textContent)).toEqual(['Ads', 'Web', 'Presentations', 'Other'])
    expect(screen.queryByRole('tablist', { name: 'Web asset types' })).not.toBeInTheDocument()
    fireEvent.mouseDown(screen.getByRole('tab', { name: 'Other' }))
    expect(screen.getByRole('heading', { name: 'Business card' })).toBeVisible()
    fireEvent.mouseDown(screen.getByRole('tab', { name: 'Ads' }))
    expect(screen.queryByRole('tablist', { name: 'Ads asset types' })).not.toBeInTheDocument()
    window.history.replaceState({}, '', '/mvp/templates?category=websites')
    fireEvent.popState(window)
    expect(screen.getByRole('tab', { name: 'Web' })).toHaveAttribute('aria-selected', 'true')
    expect(screen.queryByRole('tablist', { name: 'Web asset types' })).not.toBeInTheDocument()
  })
  test('shows banner previews in an elevated gallery without captions', () => {
    window.history.replaceState({}, '', '/mvp/templates')
    const templates = studioTemplates.map(manifest => ({ id: manifest.id, name: manifest.name, manifest }))
    render(<TemplateLibrary templates={templates} onChoose={vi.fn()} />)
    expect(screen.getByRole('region', { name: 'Novartis V1 templates' })).toBeVisible()
    expect(document.querySelectorAll('.nv-template-gallery img')).toHaveLength(1)
    expect(document.querySelector('.bs-template-gallery')).toBeInTheDocument()
    expect(screen.getByRole('heading', { name: 'Campaign banner' })).toBeVisible()
    expect(screen.getByRole('heading', { name: 'Editorial split' })).toBeVisible()
    expect(screen.getByRole('heading', { name: 'Product spotlight' })).toBeVisible()
    expect(screen.getByRole('heading', { name: 'Bold announcement' })).toBeVisible()
    expect(screen.getAllByText(/1080 ×/)).toHaveLength(3)
    expect(screen.queryByRole('button', { name: /^Use template$/ })).not.toBeInTheDocument()
  })

  test('opens the direct tab and keeps all slides out of banner campaign selection', () => {
    const onChoose = vi.fn()
    render(<TemplateLibrary templates={studioTemplates.map(manifest => ({ id: manifest.id, name: manifest.name, manifest }))} onChoose={onChoose} />)
    expect(screen.getByRole('tab', { name: 'Presentations' })).toHaveAttribute('aria-selected', 'true')
    expect(screen.getAllByRole('button', { name: /^Open .* slide$/ })).toHaveLength(5)
    fireEvent.mouseDown(screen.getByRole('tab', { name: 'Ads' }))
    expect(screen.queryByRole('region', { name: 'MSD presentation templates' })).not.toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Use Editorial split template' }))
    expect(onChoose).not.toHaveBeenCalled()
    expect(screen.getByRole('textbox', { name: 'Headline' })).toBeVisible()
    expect(screen.getByRole('tab', { name: 'Content', selected: true })).toBeVisible()
  })
  test('edits, validates AI responses and persists the text draft', async () => {
    const onChoose = vi.fn()
    render(<TemplateLibrary templates={[]} onChoose={onChoose} />)
    fireEvent.click(screen.getByRole('button', { name: 'Open Opening slide' }))
    await waitFor(() => expect(screen.getByRole('button', { name: 'Save text draft' })).toBeEnabled())
    const input = screen.getByRole('textbox', { name: 'Generated content JSON' })
    fireEvent.change(input, { target: { value: '{"extra":"no"}' } })
    fireEvent.click(screen.getByRole('button', { name: 'Apply content' }))
    expect(screen.getByRole('alert')).toHaveTextContent('Unknown field: extra.')
    const values = { ...createMsdPresentationTemplates()[0].sampleValues, headline: 'A new perspective.' }
    fireEvent.change(input, { target: { value: JSON.stringify(values) } })
    fireEvent.click(screen.getByRole('button', { name: 'Apply content' }))
    expect(screen.queryByRole('alert')).not.toBeInTheDocument()
    expect(screen.getByRole('textbox', { name: /^Headline/ })).toHaveValue('A new perspective.')
    fireEvent.click(screen.getByRole('button', { name: 'Save text draft' }))
    expect(JSON.parse(localStorage.getItem('studio:slide-draft:msd-slide-opening:1.0.0')).headline).toBe('A new perspective.')
    expect(onChoose).not.toHaveBeenCalled()
  })
})
