import { useState, type ComponentType, type ReactNode } from 'react'
import { Container, Divider, Heading, Icon, Inline, Stack, Surface, Text } from '../../atoms'
import {
  Alert, AttachmentArea, Breadcrumbs, Button, Checkbox, Combobox, DatePicker, Dialog, Drawer, FeedbackButton,
  EmptyState, FileDropzone, FileList, Form, FormActions, InlineConfirmation, InlineText,
  Menu, MultiSelect, NavigationList, NumberStepper, Pagination, Panel, PasswordField,
  Popover, ProgressBar, ProgressRing, RadioGroup, RangeSlider, Rating, SearchField, Select,
  SegmentedControl, Skeleton, Slider, Spinner, StatusBadge, Table, Tabs, Tag, TextAction,
  TextArea, TextField, Toast, Toggle, Tooltip, WorkflowSteps,
  Accordion, Avatar, AvatarGroup, AvatarGroupCompact, Badge, Banner, ButtonGroup, ColorPicker,
  CommandMenu, CompactButton, DigitInput, DotStepper, FancyButton, Hint, Kbd, Label, Notification,
  TabMenuVertical, VerticalStepper,
  type FileItem,
} from '../../components'
import { CodeExample } from '../../ui-blocks/CodeExample'

export type ComponentReferenceRow = { name: string; value: string; purpose: string }
export type ComponentExample = { id: string; title: string; description?: string; source: string; preview: ComponentType }
export type ComponentSpec = {
  id: string
  title: string
  displayTitle?: string
  overviewTitle?: string
  category: string
  description: string
  source: string
  preview: ComponentType
  example?: { title: string; description: string; preview: ComponentType }
  examples?: ComponentExample[]
  composition?: ComponentExample
  reference: ComponentReferenceRow[]
  notes: string[]
}

const rows = (...items: [string, string, string][]): ComponentReferenceRow[] => items.map(([name, value, purpose]) => ({ name, value, purpose }))
const snippet = (imports: string, body: string) => `import { ${imports} } from 'brutalist-design-system'\n\nexport function Example() {\n  return ${body}\n}`

function ButtonPreview() { const [result, setResult] = useState(''); return <Stack gap={3}><Button variant="primary" onClick={() => setResult('Button activated')}>Button</Button>{result && <Text role="status" variant="small">{result}</Text>}</Stack> }
function ButtonPrimaryPreview() { return <Button variant="primary">Get started</Button> }
function ButtonNeutralPreview() { return <Button>Learn more</Button> }
function ButtonErrorPreview() { return <Button variant="danger">Try again</Button> }
function ButtonSizePreview() { return <Inline gap={3} className="docs-button-size-row">{(['medium', 'small', 'xsmall', 'xxsmall'] as const).map(size => <Button key={size} size={size} variant="primary">{size === 'medium' ? 'Medium' : size === 'xsmall' ? 'Xsmall' : size === 'xxsmall' ? 'Xxsmall' : 'Small'}</Button>)}</Inline> }
function ButtonDisabledPreview() { return <Inline gap={3}><Button variant="primary" disabled>Disabled</Button><Button disabled>Disabled</Button><Button variant="danger" disabled>Disabled</Button></Inline> }
function ButtonIconPreview() { return <Inline gap={3}><Button variant="primary" icon="plus">Create</Button><Button icon="arrowRight" iconPosition="end">Continue</Button><Button variant="danger" icon="delete">Delete</Button></Inline> }
function ButtonFullWidthPreview() { return <Button className="docs-button-full-width" variant="primary">Learn more</Button> }
function ButtonCustomColorPreview() { return <Button style={{ backgroundColor: '#f2b84b' }}>Brand action</Button> }
function ButtonAsChildPreview() { return <TextAction href="#reference">As link</TextAction> }
function ButtonCompositionPreview() { function ActionButton({ children }: { children: ReactNode }) { return <Button variant="primary" size="compact">{children}</Button> } return <ActionButton>Save changes</ActionButton> }
function FeedbackButtonPreview() { return <FeedbackButton label="Copy value" successLabel="Copied" icon="copy" successIcon="check" onAction={() => Promise.resolve()} /> }
function TextActionPreview() { return <Inline gap={4}><TextAction href="#component-text-action">Read the guide</TextAction><TextAction onClick={() => undefined}>Run action</TextAction></Inline> }
function FormActionsPreview() { return <Form label="Example form" onSubmit={event => event.preventDefault()}><TextField label="Project name" defaultValue="Oslo launch" /><FormActions onCancel={() => undefined} message="Actions belong at the end of a form." /></Form> }
function InlineConfirmationPreview() { const [confirmed, setConfirmed] = useState(false); return <Stack gap={3}><InlineConfirmation label="Delete draft" question="Delete this draft?" description="This demo keeps the action inline until you confirm." onConfirm={() => setConfirmed(true)} />{confirmed && <Text role="status" variant="small">Draft deleted.</Text>}</Stack> }
function TablePreview() { const data = [{ id: 'brief', name: 'Project brief', owner: 'Mira' }, { id: 'review', name: 'Creative review', owner: 'Jonas' }]; return <Table label="Projects" rows={data} rowKey={row => row.id} columns={[{ id: 'name', header: 'Project', render: row => <Text>{row.name}</Text>, sortable: true }, { id: 'owner', header: 'Owner', render: row => <Text variant="small">{row.owner}</Text> }]} /> }
function TagPreview() { return <Tag>Planned</Tag> }
function TagIconPreview() { return <Tag icon="Sparkles">Featured</Tag> }
function TagStatusColorsPreview() { return <Inline gap={2}><Tag>Planned</Tag><Tag tone="accent" icon="clock">In progress</Tag><Tag tone="accent" icon="Sparkles">In review</Tag><Tag tone="success" status="success">Approved</Tag><Tag tone="danger" status="danger">Blocked</Tag></Inline> }
function TagRemovablePreview() { return <Tag onRemove={() => undefined} removeLabel="Remove project tag">Project</Tag> }
function ProgressBarPreview() { return <ProgressBar label="Export progress" value={68} /> }
function ProgressRingPreview() { return <ProgressRing label="Storage" value={72} description="72% used" /> }
function RatingPreview() { const [value, setValue] = useState(4); return <Rating label="Rate this example" value={value} onChange={setValue} /> }
function AlertPreview() { return <Stack gap={3}><Alert title="Saved" description="Your changes are ready for review." tone="success" variant="light" /><Alert title="Check the fields" description="Color is paired with a message and icon." tone="danger" variant="stroke" action={<TextAction href="#reference">Review</TextAction>} /><Alert title="Export delayed" description="One format is still rendering." tone="warning" variant="lighter" /><Alert title="New feature available" description="Try the updated project workflow." tone="feature" variant="filled" /></Stack> }
function AlertFilledPreview() { return <Stack gap={3}><Alert title="Project saved" description="Your changes are ready for review." tone="success" variant="filled" /><Alert title="Brief needs attention" description="Add a CTA before export." tone="danger" variant="filled" /></Stack> }
function AlertLightPreview() { return <Stack gap={3}><Alert title="Project saved" description="Your changes are ready for review." tone="success" variant="light" /><Alert title="Export delayed" description="One format is still rendering." tone="warning" variant="light" /></Stack> }
function AlertLighterPreview() { return <Stack gap={3}><Alert title="New feature available" description="Try the updated project workflow." tone="feature" variant="lighter" /><Alert title="Check the fields" description="Color is paired with a message and icon." tone="danger" variant="lighter" /></Stack> }
function AlertStrokePreview() { return <Stack gap={3}><Alert title="Saved" description="Your changes are ready for review." tone="success" variant="stroke" /><Alert title="Check the fields" description="Color is paired with a message and icon." tone="danger" variant="stroke" action={<TextAction href="#reference">Review</TextAction>} /></Stack> }
function AlertSizePreview() { return <Stack gap={3}><Alert title="Compact alert" description="Small keeps dense lists readable." tone="info" size="small" /><Alert title="Detailed alert" description="Large adds room for longer context and a follow-up action." tone="info" size="large" action={<TextAction href="#reference">Learn more</TextAction>} /></Stack> }
function ToastPreview() { const [visible, setVisible] = useState(true); return visible ? <Toast title="Draft saved" description="You can continue editing." tone="success" onDismiss={() => setVisible(false)} /> : <Button onClick={() => setVisible(true)}>Show toast</Button> }
function TooltipPreview() { return <Tooltip label="Hover for help" content="Tooltips explain an unfamiliar control." /> }
function SpinnerPreview() { return <Spinner label="Loading preview" /> }
function SkeletonPreview() { return <Skeleton label="Loading rows" lines={3} /> }
function EmptyStatePreview() { return <EmptyState title="No projects" description="Create one to start planning." action={<Button variant="primary">Create project</Button>} /> }
function FormPreview() { return <Form label="Project settings"><TextField label="Project name" defaultValue="Nordic spring" /><TextArea label="Description" defaultValue="A short project description." /><Checkbox label="Include animated formats" defaultChecked /><Toggle label="Publish automatically" /><FormActions /></Form> }
function TextFieldPreview() { const [value, setValue] = useState('Nordic spring'); return <Stack gap={4}><TextField label="Project title" value={value} onChange={event => setValue(event.target.value)} instructions="Keep it short and descriptive." /><TextField label="Read-only ID" value="project-001" readOnly /></Stack> }
function SearchPreview() { const [value, setValue] = useState(''); return <SearchField label="Search projects" placeholder="Search by name" value={value} onChange={setValue} /> }
function PasswordPreview() { return <PasswordField label="Workspace password" defaultValue="secret" instructions="Use at least twelve characters." /> }
function TextAreaPreview() { return <TextArea label="Project brief" rows={4} placeholder="Describe the project" instructions="Markdown is supported." /> }
function CheckboxPreview() { const [mixed, setMixed] = useState(true); return <Stack gap={3}><Checkbox label="Select all formats" indeterminate={mixed} checked={!mixed} onChange={event => setMixed(!event.target.checked)} /><Checkbox label="Include motion" defaultChecked /></Stack> }
function RadioPreview() { const [value, setValue] = useState('square'); return <RadioGroup label="Export format" value={value} onChange={setValue} options={[{ value: 'square', label: 'Square' }, { value: 'portrait', label: 'Portrait' }, { value: 'landscape', label: 'Landscape', disabled: true }]} /> }
function TogglePreview() { const [checked, setChecked] = useState(false); return <Toggle label="Publish automatically" checked={checked} onChange={event => setChecked(event.target.checked)} instructions="Turn this on to publish after approval." /> }
const selectOptions = [{ value: 'brief', label: 'Project brief' }, { value: 'review', label: 'Creative review' }, { value: 'delivery', label: 'Delivery', disabled: true }]
function DropdownPreview() { const [select, setSelect] = useState('brief'); const [combo, setCombo] = useState('brief'); const [multi, setMulti] = useState<string[]>(['review']); return <Stack gap={4}><Select label="Select a project" options={selectOptions} value={select} onValueChange={setSelect} /><Combobox label="Find a project" options={selectOptions} value={combo} onChange={setCombo} /><MultiSelect label="Filter projects" options={selectOptions} value={multi} onChange={setMulti} /></Stack> }
function DatePickerPreview() { const [date, setDate] = useState('2026-09-15'); return <DatePicker label="Launch date" value={date} onValueChange={setDate} /> }
function NumberStepperPreview() { const [value, setValue] = useState(3); return <NumberStepper label="Variants" value={value} onChange={setValue} min={1} max={10} /> }
function SliderPreview() { const [value, setValue] = useState(64); return <Slider label="Quality" value={value} onChange={setValue} formatValue={value => `${value}%`} /> }
function RangeSliderPreview() { const [value, setValue] = useState<[number, number]>([20, 80]); return <RangeSlider label="Budget range" value={value} onChange={setValue} lowerLabel="Minimum" upperLabel="Maximum" /> }
function FilesPreview() { const files: FileItem[] = [{ id: 'brief', name: 'project-brief.pdf', size: 24000 }, { id: 'copy', name: 'headline.md', size: 3400 }]; return <Stack gap={4}><FileDropzone label="Upload creative files" size="small" multiple onFiles={() => undefined} accept=".pdf,.md" /><FileList files={files} onRemove={() => undefined} /></Stack> }
function AttachmentPreview() { return <AttachmentArea label="Project attachments" onFiles={() => undefined}><TextArea label="Add a note" placeholder="Drop files or write a note" embedded /></AttachmentArea> }
function InlineTextPreview() { const [value, setValue] = useState('Editable project title'); return <InlineText label="Project title" value={value} onSave={next => setValue(next)} /> }
function PanelPreview() { return <Panel title="Project brief" description="Panel groups a heading, supporting copy and content."><Text>Content stays on a shared surface.</Text></Panel> }
function TabsPreview() {
  const [tab, setTab] = useState('overview')
  const items = [{ id: 'overview', label: 'Overview', content: <Text>Overview content.</Text> }, { id: 'activity', label: 'Activity', content: <Text>Activity content.</Text> }]
  return <Stack gap={4}>
    <Stack gap={1}><Text variant="small" tone="secondary">Compact</Text><Tabs label="Project sections compact" size="compact" value={tab} onChange={setTab} items={items} /></Stack>
    <Stack gap={1}><Text variant="small" tone="secondary">Default</Text><Tabs label="Project sections default" size="default" items={items} /></Stack>
  </Stack>
}
function SegmentedControlPreview() {
  const options = [{ value: 'grid', label: 'Grid' }, { value: 'list', label: 'List' }]
  return <Stack gap={4}>
    <Stack gap={1}><Text variant="small" tone="secondary">Compact</Text><SegmentedControl label="View compact" size="compact" options={options} /></Stack>
    <Stack gap={1}><Text variant="small" tone="secondary">Default</Text><SegmentedControl label="View default" size="default" options={options} /></Stack>
  </Stack>
}
function BreadcrumbPreview() { return <Breadcrumbs items={[{ label: 'Projects', href: '#' }, { label: 'Nordic spring', href: '#' }, { label: 'Brief' }]} /> }
function PaginationPreview() { const [page, setPage] = useState(2); return <Pagination page={page} pageCount={5} onPageChange={setPage} /> }
function NavigationPreview() { return <NavigationList label="Project navigation" items={[{ id: 'overview', label: 'Overview', href: '#', icon: 'LayoutDashboard', current: true }, { id: 'settings', label: 'Settings', href: '#', icon: 'settings' }]} /> }
function WorkflowPreview() { const [current, setCurrent] = useState('review'); return <WorkflowSteps label="Project workflow" current={current} onChange={setCurrent} steps={[{ id: 'brief', label: 'Brief', complete: true }, { id: 'review', label: 'Review', description: 'Check copy' }, { id: 'publish', label: 'Publish', disabled: true }]} /> }
function MenuPreview() { const [result, setResult] = useState(''); return <Stack gap={3}><Menu label="More actions" items={[{ id: 'edit', label: 'Edit', icon: 'edit' }, { id: 'duplicate', label: 'Duplicate', icon: 'copy' }, { id: 'delete', label: 'Delete', danger: true }]} onSelect={setResult} />{result && <Text role="status" variant="small">Selected: {result}</Text>}</Stack> }
function DialogPreview() { return <Dialog title="Delete draft" description="This dialog asks for confirmation before the action." trigger="Delete draft"><Inline gap={3}><Button variant="danger" onClick={() => undefined}>Delete</Button><Button>Cancel</Button></Inline></Dialog> }
function DrawerPreview() { return <Drawer title="Documentation" description="A drawer keeps secondary navigation available on small screens." trigger="Open drawer"><NavigationList label="Drawer links" items={[{ id: 'overview', label: 'Overview', href: '#' }, { id: 'settings', label: 'Settings', href: '#' }]} /></Drawer> }
function PopoverPreview() { return <Popover label="More information"><Stack gap={2}><Text variant="small">Popover content is positioned by the shared overlay primitive.</Text><Button size="compact">Continue</Button></Stack></Popover> }
function ButtonGroupPreview() { return <ButtonGroup><Button>Save</Button><Button>Save as draft</Button><Button iconOnly icon="more" aria-label="More save actions" /></ButtonGroup> }
function CompactButtonPreview() { return <Inline gap={3}><CompactButton icon="edit">Edit</CompactButton><CompactButton iconOnly icon="settings" aria-label="Settings" /></Inline> }
function FancyButtonPreview() { return <FancyButton variant="primary" size="compact" icon="arrowRight" iconPosition="end" subtitle="Open workspace">Continue</FancyButton> }
function AvatarPreview() { return <Inline gap={3}><Avatar name="Mira Chen" /><Avatar name="Jonas Weber" status="online" /><Avatar name="No image" status="offline" /></Inline> }
function AvatarGroupPreview() { return <AvatarGroup label="Project members" items={[{ name: 'Mira Chen' }, { name: 'Jonas Weber' }, { name: 'Alex Kim' }, { name: 'Sam Lee' }, { name: 'Priya Shah' }]} max={3} /> }
function AvatarGroupCompactPreview() { return <AvatarGroupCompact label="Compact members" items={[{ name: 'Mira Chen' }, { name: 'Jonas Weber' }, { name: 'Alex Kim' }]} /> }
function BadgePreview() { return <Inline gap={2}><Badge tone="neutral">Draft</Badge><Badge tone="accent" icon="clock">In review</Badge><Badge tone="success" icon="check">Approved</Badge><Badge tone="danger" icon="alert">Blocked</Badge></Inline> }
function BannerPreview() { const [visible, setVisible] = useState(true); return visible ? <Banner title="Scheduled maintenance" description="The workspace will be read-only for five minutes." tone="warning" action={<TextAction href="#reference" className="c-banner__action">Details</TextAction>} onDismiss={() => setVisible(false)} /> : <Button onClick={() => setVisible(true)}>Show banner</Button> }
function DividerPreview() { return <Stack gap={3}><Text>Before the divider</Text><Divider /><Text>After the divider</Text></Stack> }
function KbdPreview() { return <Inline gap={1}><Kbd>⌘</Kbd><Kbd>K</Kbd><Text variant="small" tone="secondary">opens quick search</Text></Inline> }
function NotificationPreview() { return <Notification title="Export complete" description="Your files are ready to download." tone="success" actions={<Button size="compact">Download</Button>} /> }
function ColorPickerPreview() { const [color, setColor] = useState('#72b8ff'); return <ColorPicker label="Accent color" value={color} onChange={setColor} /> }
function DigitInputPreview() { const [value, setValue] = useState('2048'); return <DigitInput label="Verification code" value={value} onChange={setValue} /> }
function HintPreview() { return <Stack gap={2}><Label htmlFor="hint-input">Workspace slug</Label><TextField id="hint-input" label="Workspace slug" defaultValue="nordic-spring" /><Hint>Use lowercase letters and hyphens.</Hint><Hint tone="danger">That slug is already in use.</Hint></Stack> }
function LabelPreview() { return <Stack gap={2}><Label required hint="Optional help text">Project name</Label><Text variant="small" tone="secondary">Labels keep field meaning visible before interaction.</Text></Stack> }
function AccordionPreview() { return <Accordion label="Frequently asked questions" items={[{ id: 'one', title: 'What is shared?', content: <Text>Tokens and primitives are shared across every screen.</Text>, defaultOpen: true }, { id: 'two', title: 'Can I customize it?', content: <Text>Use named variants and composition props.</Text> }]} /> }
function TabMenuVerticalPreview() { return <TabMenuVertical label="Settings sections" items={[{ id: 'general', label: 'General', content: <Text>General settings content.</Text> }, { id: 'members', label: 'Members', content: <Text>Members settings content.</Text> }]} /> }
function DotStepperPreview() { const [step, setStep] = useState(1); return <DotStepper label="Checkout progress" steps={['Cart', 'Details', 'Payment', 'Done']} current={step} onChange={setStep} /> }
const verticalStepperSteps = [{ id: 'account', label: 'Create account', complete: true }, { id: 'review', label: 'Review details' }, { id: 'finish', label: 'Finish setup' }]
const verticalStepperDescriptiveSteps = [{ id: 'account', label: 'Create account', description: 'Set up your workspace profile.', complete: true }, { id: 'review', label: 'Review details', description: 'Check your information before continuing.' }, { id: 'finish', label: 'Finish setup', description: 'Invite your team and publish the workspace.' }]
function VerticalStepperHeadersPreview() { return <VerticalStepper label="Onboarding headers" current="review" steps={verticalStepperSteps} /> }
function VerticalStepperDetailsPreview() { return <VerticalStepper label="Onboarding details" current="review" steps={verticalStepperDescriptiveSteps} /> }
function VerticalStepperPreview() { return <VerticalStepperDetailsPreview /> }
function CommandMenuPreview() { return <CommandMenu label="Open command menu" items={[{ id: 'new', label: 'New project', icon: 'plus' }, { id: 'settings', label: 'Open settings', icon: 'settings' }, { id: 'help', label: 'Get help', icon: 'info' }]} onSelect={() => undefined} /> }

const buttonExamples: ComponentExample[] = [
  { id: 'primary', title: 'Primary (Default)', description: 'Use the accent action for the main path through a view.', source: snippet('Button', '<Button variant="primary">Get started</Button>'), preview: ButtonPrimaryPreview },
  { id: 'neutral', title: 'Neutral', description: 'Use the neutral action for supporting or secondary work.', source: snippet('Button', '<Button>Learn more</Button>'), preview: ButtonNeutralPreview },
  { id: 'error', title: 'Error', description: 'Use the danger treatment for destructive or recovery actions.', source: snippet('Button', '<Button variant="danger">Try again</Button>'), preview: ButtonErrorPreview },
  { id: 'size', title: 'Size', description: 'Choose a named size to match the surrounding density.', source: snippet('Button', '<Inline gap={3}>\n  <Button size="medium">Medium</Button>\n  <Button size="small">Small</Button>\n  <Button size="xsmall">Xsmall</Button>\n  <Button size="xxsmall">Xxsmall</Button>\n</Inline>'), preview: ButtonSizePreview },
  { id: 'disabled', title: 'Disabled', description: 'Disabled actions remain visible while preventing activation.', source: snippet('Button', '<Button variant="primary" disabled>Disabled</Button>'), preview: ButtonDisabledPreview },
  { id: 'with-icon', title: 'With Icon', description: 'Pair a concise verb with an icon when it improves recognition.', source: snippet('Button', '<Button variant="primary" icon="plus">Create</Button>'), preview: ButtonIconPreview },
  { id: 'full-width', title: 'Full Width', description: 'Use the full-width composition when the action owns the available row.', source: snippet('Button', '<Button className="docs-button-full-width" variant="primary">Learn more</Button>'), preview: ButtonFullWidthPreview },
  { id: 'custom-color', title: 'Custom color', description: 'Use the native style prop when a product action needs a specific brand color.', source: snippet('Button', '<Button style={{ backgroundColor: "#f2b84b" }}>Brand action</Button>'), preview: ButtonCustomColorPreview },
  { id: 'as-child', title: 'asChild', description: 'Use a text action when the same visual action should navigate as a link.', source: snippet('TextAction', '<TextAction href="/guide">As link</TextAction>'), preview: ButtonAsChildPreview },
]
const buttonComposition: ComponentExample = { id: 'composition', title: 'Button composition', description: 'Create a small wrapper when an action has a consistent product-specific meaning.', source: "import { Button } from 'brutalist-design-system'\n\nfunction SaveButton() {\n  return <Button variant=\"primary\" size=\"compact\">Save changes</Button>\n}\n\nexport function Toolbar() {\n  return <SaveButton />\n}" , preview: ButtonCompositionPreview }
const alertExamples: ComponentExample[] = [
  { id: 'filled', title: 'Filled', description: 'Use a solid semantic surface when the alert must command attention.', source: snippet('Alert', '<Alert variant="filled" tone="success" title="Project saved" description="Your changes are ready for review." />'), preview: AlertFilledPreview },
  { id: 'light', title: 'Light', description: 'Use a tinted surface when the message should stay prominent without feeling heavy.', source: snippet('Alert', '<Alert variant="light" tone="warning" title="Export delayed" description="One format is still rendering." />'), preview: AlertLightPreview },
  { id: 'lighter', title: 'Lighter', description: 'Use the softest semantic treatment for supporting context in a content flow.', source: snippet('Alert', '<Alert variant="lighter" tone="feature" title="New feature available" />'), preview: AlertLighterPreview },
  { id: 'stroke', title: 'Stroke', description: 'Use an outlined treatment when the message belongs beside other content.', source: snippet('Alert', '<Alert variant="stroke" tone="danger" title="Check the fields" action={<TextAction>Review</TextAction>} />'), preview: AlertStrokePreview },
  { id: 'size', title: 'Size', description: 'Choose a compact or spacious layout based on the amount of context.', source: snippet('Alert', '<Alert size="large" tone="info" title="Detailed alert" description="Longer context can live here." />'), preview: AlertSizePreview },
]
const verticalStepperExamples: ComponentExample[] = [
  { id: 'headers-only', title: 'Headers only', description: 'Use the compact form when the step names are self-explanatory.', source: snippet('VerticalStepper', '<VerticalStepper label="Onboarding" current="review" steps={steps} onChange={setStep} />'), preview: VerticalStepperHeadersPreview },
  { id: 'with-descriptions', title: 'With descriptions', description: 'Add a description when a step needs context or an instruction.', source: snippet('VerticalStepper', '<VerticalStepper label="Onboarding" current="review" steps={stepsWithDescriptions} onChange={setStep} />'), preview: VerticalStepperDetailsPreview },
]

const tagExamples: ComponentExample[] = [
  { id: 'with-icon', title: 'With icon', description: 'Add an icon when the tag needs a quick visual cue.', source: snippet('Tag', '<Tag icon="Sparkles">Featured</Tag>'), preview: TagIconPreview },
  { id: 'status-colors', title: 'Status colors', description: 'Use status-colored tags for workflow states that must scan as a set.', source: snippet('Tag', '<Inline gap={2}><Tag>Planned</Tag><Tag tone="accent" icon="clock">In progress</Tag><Tag tone="accent" icon="Sparkles">In review</Tag><Tag tone="success" status="success">Approved</Tag><Tag tone="danger" status="danger">Blocked</Tag></Inline>'), preview: TagStatusColorsPreview },
  { id: 'removable', title: 'Removable', description: 'Use the removal affordance for filters and editable metadata.', source: snippet('Tag', '<Tag onRemove={removeTag} removeLabel="Remove project tag">Project</Tag>'), preview: TagRemovablePreview },
]

const common = (id: string, title: string, category: string, description: string, preview: ComponentType, source: string, reference: ComponentReferenceRow[], notes: string[], example?: ComponentSpec['example'], examples?: ComponentExample[], composition?: ComponentExample): ComponentSpec => ({ id, title, category, description, preview, source, reference, notes, example, examples, composition })

export const componentPages: ComponentSpec[] = [
  common('button', 'Button', 'Actions', 'Buttons trigger an action and communicate their importance through a shared variant, size and state model.', ButtonPreview, snippet('Button', '<Button variant="primary" icon="plus">Create project</Button>'), rows(['variant', 'primary | secondary | danger | quiet', 'Visual importance; defaults to secondary.'], ['size', 'default | compact | medium | small | xsmall | xxsmall', 'Named sizes map to our shared control density tokens.'], ['icon / iconPosition', 'IconName / start | end', 'Optional leading or trailing icon.'], ['busy / disabled', 'boolean', 'Busy blocks repeat activation and disabled prevents input.']), ['Prefer a verb that describes the result. Keep one primary action in a group.', 'Icon-only buttons require an accessible aria-label.'], undefined, buttonExamples, buttonComposition),
  common('feedback-button', 'Feedback button', 'Actions', 'A reusable action button that shows completion in place of a separate status message.', FeedbackButtonPreview, snippet('FeedbackButton', '<FeedbackButton label="Copy value" successLabel="Copied" icon="copy" successIcon="check" onAction={copyValue} />'), rows(['label / successLabel', 'string', 'Idle and completed button labels.'], ['icon / successIcon', 'IconName?', 'Idle and completed icons.'], ['onAction', '() => void | Promise<void>', 'Action that must resolve before completion is shown.'], ['resetKey / onError', 'string | number? / callback?', 'Reset completion for new content and handle failures.']), ['Use the completed label as confirmation that the action succeeded. Keep failures in the owning workflow.']),
  common('text-action', 'Text action', 'Actions', 'A low-emphasis action that keeps the surrounding sentence or list compact.', TextActionPreview, snippet('TextAction', '<TextAction href="/guide">Read the guide</TextAction>'), rows(['href', 'string | undefined', 'Renders a link when provided; otherwise a button.'], ['disabled', 'boolean', 'Prevents the button action.']), ['Use this for inline navigation or a secondary action.']),
  common('form-actions', 'Form actions', 'Actions', 'A consistent submit and cancel row for forms, including busy and status feedback.', FormActionsPreview, snippet('Form, FormActions, TextField', '<FormActions onCancel={onCancel} submitLabel="Save" />'), rows(['submitLabel / cancelLabel', 'string', 'Action labels; defaults Save and Cancel.'], ['busy / disabled', 'boolean', 'Busy changes the submit button state.'], ['message', 'ReactNode', 'Optional status text below the buttons.']), ['Place FormActions as the last child of Form.']),
  common('inline-confirmation', 'Inline confirmation', 'Actions', 'A compact confirmation pattern that reveals the question in place of a separate dialog.', InlineConfirmationPreview, snippet('InlineConfirmation', '<InlineConfirmation label="Delete draft" question="Delete this draft?" onConfirm={removeDraft} />'), rows(['label / question', 'string', 'Trigger label and confirmation prompt.'], ['onConfirm', '() => void | Promise<void>', 'Runs after confirmation.'], ['description / disabled', 'string? / boolean?', 'Supporting copy and disabled state.']), ['Use Dialog when the decision needs more context or an explicit cancel action.']),
  common('table', 'Table', 'Displaying Data', 'Tables expose structured rows with optional sorting and an accessible scroll region.', TablePreview, snippet('Table', '<Table label="Projects" rows={rows} rowKey={row => row.id} columns={columns} />'), rows(['label / rows / rowKey', 'string / readonly T[] / (row) => string', 'Accessible name and stable row identity.'], ['columns', 'readonly TableColumn<T>[]', 'Headers and cell renderers.'], ['sort / onSort', 'TableSort? / callback?', 'Optional controlled sorting.'], ['emptyMessage', 'string', 'Message for an empty table.']), ['Keep column headers short and provide a meaningful empty state.']),
  common('tag', 'Tag', 'Displaying Data', 'Tags label an item or status at a glance, with optional icon and removal affordance.', TagPreview, snippet('Tag', '<Tag>Planned</Tag>'), rows(['tone', 'neutral | accent | success | danger', 'Color treatment; neutral is the plain white tag.'], ['status', 'TagStatus?', 'Status icon/state when supported.'], ['icon', 'IconName?', 'Optional leading icon.'], ['onRemove / removeLabel', 'callback? / string?', 'Optional removal action.']), ['Use the plain tag for neutral labels. Move status, icon and removable treatments into the variant that matches the workflow.'], undefined, tagExamples),
  common('progress-bar', 'Progress bar', 'Displaying Data', 'A horizontal indicator for a measurable task or value range.', ProgressBarPreview, snippet('ProgressBar', '<ProgressBar label="Export progress" value={68} />'), rows(['label', 'string', 'Accessible name.'], ['value / max', 'number? / number', 'Current and maximum values.'], ['showValue', 'boolean', 'Whether the percentage is visible.']), ['Keep the label visible when progress is important to understanding the task.']),
  common('progress-ring', 'Progress ring', 'Displaying Data', 'A compact circular indicator for capacity or task completion.', ProgressRingPreview, snippet('ProgressRing', '<ProgressRing label="Storage" value={72} description="72% used" />'), rows(['label / value / max', 'string / number / number', 'Accessible name and range.'], ['description', 'string?', 'Supporting text beside the ring.']), ['Use a ring when the value belongs to a compact summary; keep it on its own page when a circular summary is the focus.']),
  common('rating', 'Rating', 'Displaying Data', 'A keyboard-accessible star rating with a controlled numeric value.', RatingPreview, snippet('Rating', '<Rating label="Rate this example" value={4} onChange={setValue} />'), rows(['label / value / max', 'string / number / number', 'Accessible name, selected value and number of stars.'], ['onChange', '(value: number) => void', 'Receives the selected value.'], ['disabled', 'boolean?', 'Prevents changes.']), ['Include a text label; the stars are a visual representation of the value.']),
  common('alert', 'Alert', 'Feedback', 'An inline message for a state that belongs in the current content flow.', AlertPreview, snippet('Alert', '<Alert variant="light" tone="success" title="Saved" description="Your changes are ready." />'), rows(['title / description', 'string / ReactNode?', 'Primary message and supporting detail.'], ['tone', 'neutral | success | danger | warning | info | feature', 'Semantic status.'], ['variant', 'filled | light | lighter | stroke', 'Surface treatment.'], ['size', 'small | large', 'Density and context allowance.'], ['showIcon / announce', 'boolean', 'Icon visibility and live announcement.'], ['action', 'ReactNode?', 'Optional action control.']), ['Use announce for updates that need immediate assistive-technology feedback.', 'Use filled for high-priority messages and stroke for quieter inline context.'], undefined, alertExamples),
  common('toast', 'Toast', 'Feedback', 'A transient status message with a consistent dismiss action.', ToastPreview, snippet('Toast', '<Toast title="Draft saved" onDismiss={hideToast} />'), rows(['title / description', 'string / ReactNode?', 'Message content.'], ['tone', 'neutral | success | danger', 'Semantic treatment.'], ['onDismiss', '() => void', 'Dismisses the toast.']), ['Keep the message short and do not hide essential information only in a toast.']),
  common('tooltip', 'Tooltip', 'Feedback', 'A short explanation shown on hover or focus for an unfamiliar control.', TooltipPreview, snippet('Tooltip', '<Tooltip label="Hover for help" content="Explain this setting." />'), rows(['label', 'string', 'Trigger text.'], ['content', 'string', 'Tooltip explanation.']), ['Tooltips supplement labels; they should not carry required instructions alone.']),
  common('spinner', 'Spinner', 'Feedback', 'A compact live indicator for work that has not completed.', SpinnerPreview, snippet('Spinner', '<Spinner label="Loading preview" />'), rows(['label', 'string', 'Accessible live status.']), ['Use a specific label such as “Saving project” instead of “Loading” when possible.']),
  common('skeleton', 'Skeleton', 'Feedback', 'Placeholder lines preserve layout while content is loading.', SkeletonPreview, snippet('Skeleton', '<Skeleton label="Loading rows" lines={3} />'), rows(['label', 'string?', 'Accessible status label.'], ['lines', 'number · 1–10', 'Number of placeholder lines.']), ['Match the expected content shape and replace it when data arrives.']),
  common('empty-state', 'Empty state', 'Feedback', 'A quiet surface that explains an empty collection and offers a next step.', EmptyStatePreview, snippet('EmptyState', '<EmptyState title="No projects" description="Create one to start." action={<Button>Create</Button>} />'), rows(['title', 'string', 'Primary explanation.'], ['description / action', 'string? / ReactNode?', 'Supporting guidance and optional next action.']), ['Explain why the space is empty and what the user can do next.']),
  common('form', 'Form', 'Form', 'A labeled vertical form wrapper that uses the shared spacing scale.', FormPreview, snippet('Form', '<Form label="Project settings">{children}</Form>'), rows(['label', 'string', 'Accessible form name.'], ['native form props', 'FormHTMLAttributes', 'Submit, method and native form behavior.']), ['Keep field validation close to its field and finish with FormActions.']),
  common('text-field', 'Text field', 'Form', 'A single-line input with instructions, validation and native input behavior.', TextFieldPreview, snippet('TextField', '<TextField label="Project title" value={title} onChange={onChange} />'), rows(['label', 'ReactNode', 'Visible and accessible field label.'], ['instructions / error', 'ReactNode?', 'Supporting and invalid-state messages.'], ['width', 'full | content', 'Sizing; defaults to full for text.'], ['trailing', 'ReactNode?', 'Trailing content inside the field.']), ['Use readOnly for values users can copy but not edit; use disabled when unavailable.']),
  common('search-field', 'Search field', 'Form', 'A text field with a clear affordance and a value callback for filtering.', SearchPreview, snippet('SearchField', '<SearchField label="Search projects" value={query} onChange={setQuery} />'), rows(['label / value', 'string / string', 'Accessible label and controlled value.'], ['onChange', '(value: string) => void', 'Called with the new query.'], ['autoFocus / placeholder', 'boolean? / string?', 'Initial focus and hint.']), ['Keep search state in the owning screen so navigation and results stay synchronized.']),
  common('password-field', 'Password field', 'Form', 'A password input that preserves the TextField label and validation contract.', PasswordPreview, snippet('PasswordField', '<PasswordField label="Workspace password" />'), rows(['label', 'string', 'Visible and accessible label.'], ['native input props', 'InputHTMLAttributes', 'Autocomplete, name, required and validation.']), ['Set an appropriate autocomplete value when used for authentication.']),
  common('textarea', 'Text area', 'Form', 'A multiline field for descriptions, notes and longer text.', TextAreaPreview, snippet('TextArea', '<TextArea label="Project brief" rows={4} />'), rows(['label / rows', 'ReactNode / number', 'Label and visible height.'], ['embedded', 'boolean', 'Removes outer field chrome for composition.'], ['instructions / error', 'ReactNode?', 'Supporting and invalid-state messages.']), ['Use a concise label and give longer fields an instruction when format matters.']),
  common('checkbox', 'Checkbox', 'Form', 'A binary or mixed selection control for independent options.', CheckboxPreview, snippet('Checkbox', '<Checkbox label="Include motion" checked={included} onChange={onChange} />'), rows(['label', 'ReactNode', 'Visible and accessible label.'], ['checked / indeterminate', 'boolean', 'Controlled value and mixed state.'], ['instructions / error', 'ReactNode?', 'Supporting and invalid-state messages.']), ['Use indeterminate for a parent selection whose children are mixed.']),
  common('radio-group', 'Radio group', 'Form', 'A labeled set of mutually exclusive options with optional custom text.', RadioPreview, snippet('RadioGroup', '<RadioGroup label="Export format" options={options} value={value} onChange={setValue} />'), rows(['label / options', 'string / readonly RadioOption[]', 'Group label and choices.'], ['value / onChange', 'string? / callback', 'Controlled selected option.'], ['customOption', 'object?', 'Optional text-backed choice.'], ['error / disabled', 'ReactNode? / boolean', 'Validation and availability.']), ['Use RadioGroup when users should see all mutually exclusive options at once.']),
  common('toggle', 'Toggle', 'Form', 'A binary setting control for an immediate preference or mode.', TogglePreview, snippet('Toggle', '<Toggle label="Publish automatically" checked={enabled} onChange={onChange} />'), rows(['label', 'ReactNode', 'Visible and accessible label.'], ['checked / defaultChecked', 'boolean?', 'Controlled or initial state.'], ['instructions / error', 'ReactNode?', 'Supporting and invalid-state messages.']), ['Use a checkbox when the change is part of a form submission; use Toggle for an immediate setting.']),
  common('dropdowns', 'Select / Combobox / MultiSelect', 'Form', 'Three related controls for choosing one option, searching options or choosing several.', DropdownPreview, snippet('Select, Combobox, MultiSelect', '<Select label="Project" options={options} value={value} onValueChange={setValue} />'), rows(['Select.options', 'readonly SelectOption[]', 'Options for the single-choice field.'], ['Combobox.onChange', '(value: string) => void', 'Selected option callback.'], ['MultiSelect.value', 'readonly string[]', 'Selected values.'], ['disabled / name', 'boolean? / string?', 'Availability and native form name.']), ['Select is best for a short known list; Combobox helps users search; MultiSelect exposes independent choices.']),
  common('date-picker', 'Date picker', 'Form', 'A date input that keeps the shared field label and validation behavior.', DatePickerPreview, snippet('DatePicker', '<DatePicker label="Launch date" value={date} onValueChange={setDate} />'), rows(['label / value', 'string / string?', 'Label and ISO date value.'], ['min / max', 'string?', 'Allowed date bounds.'], ['onValueChange', '(value: string) => void', 'Date callback.']), ['Store dates as ISO strings and set min/max when the domain has clear limits.']),
  common('number-stepper', 'Number stepper', 'Form', 'A numeric field with increment and decrement controls.', NumberStepperPreview, snippet('NumberStepper', '<NumberStepper label="Variants" value={value} onChange={setValue} min={1} max={10} />'), rows(['value / onChange', 'number / callback', 'Controlled numeric value.'], ['min / max / step', 'number?', 'Range and increment.'], ['instructions / disabled', 'ReactNode? / boolean', 'Supporting copy and availability.']), ['Show units in the label or instructions so the number has clear meaning.']),
  common('slider', 'Slider', 'Form', 'A keyboard-accessible range input for continuous or stepped values.', SliderPreview, snippet('Slider', '<Slider label="Quality" value={64} onChange={setValue} formatValue={formatValue} />'), rows(['value / onChange', 'number / callback', 'Controlled numeric value.'], ['min / max / step', 'number?', 'Range and increment.'], ['formatValue', '(value: number) => string', 'Visible value formatter.']), ['Always provide a label and a useful formatter when the number needs units.']),
  common('range-slider', 'Range slider', 'Form', 'Two coordinated sliders for selecting a lower and upper bound.', RangeSliderPreview, snippet('RangeSlider', '<RangeSlider label="Budget range" value={[20, 80]} onChange={setValue} />'), rows(['value / onChange', '[number, number] / callback', 'Lower and upper values.'], ['lowerLabel / upperLabel', 'string', 'Names for both handles.'], ['names', '[string, string]?', 'Optional native field names.']), ['Keep lower and upper values ordered and give each handle a meaningful label.']),
  common('file-dropzone', 'File dropzone', 'Form', 'A file picker and drop target with type, size and upload states.', FilesPreview, snippet('FileDropzone', '<FileDropzone label="Upload creative files" size="small" multiple onFiles={onFiles} />'), rows(['label / onFiles', 'string / (files: File[]) => void', 'Prompt and accepted files callback.'], ['accept / multiple', 'string? / boolean?', 'File types and count.'], ['state / progress', 'idle | uploading | success | error / number', 'Upload feedback.'], ['maxSize / onRetry', 'number? / callback?', 'Per-file limit and retry action.'], ['size', 'default | small', 'Container density for standard or compact upload surfaces.']), ['Tell users which formats and limits are accepted before they choose a file.']),
  common('file-list', 'File list', 'Form', 'A compact list of selected files with optional remove actions.', FilesPreview, snippet('FileList', '<FileList files={files} onRemove={removeFile} />'), rows(['files', 'readonly FileItem[]', 'Stable id, name and optional size.'], ['onRemove', '(id: string) => void', 'Optional remove callback.'], ['disabled', 'boolean?', 'Disables remove controls.']), ['Keep the original filename visible and preserve a stable id for each item.']),
  common('attachment-area', 'Attachment area', 'Form', 'A composed input surface for notes with an optional attachment affordance.', AttachmentPreview, snippet('AttachmentArea', '<AttachmentArea label="Attachments" onFiles={onFiles}>{children}</AttachmentArea>'), rows(['label / children', 'string / ReactNode', 'Group name and composed content.'], ['actions', 'ReactNode?', 'Additional toolbar actions.'], ['onFiles / accept / maxSize', 'callback? / string? / number?', 'Attachment behavior and limits.']), ['Use this when a note and its attachments are one coherent task.']),
  common('inline-text', 'Inline text editing', 'Form', 'Text that becomes an edit field in place and saves changes on blur or Enter.', InlineTextPreview, snippet('InlineText', '<InlineText label="Project title" value={title} onSave={saveTitle} />'), rows(['label / value', 'string / string', 'Accessible label and displayed value.'], ['onSave', '(value, sourceKey?) => void | Promise', 'Save callback; async failures keep the draft available for retry.'], ['variant / readOnly', 'TypeRole / boolean?', 'Visual role and editability.'], ['required / maxLength', 'boolean? / number?', 'Validation constraints.']), ['Use a short value for inline editing. Enter saves, Shift+Enter adds a line, and Escape restores the original value.']),
  common('panel', 'Panel', 'Layout', 'A framed grouping surface with a heading, supporting copy, filters and actions.', PanelPreview, snippet('Panel', '<Panel title="Project brief" description="Related content.">{children}</Panel>'), rows(['title / description', 'string / ReactNode?', 'Heading and supporting copy.'], ['variant', 'default | split', 'Split separates header from content.'], ['filters / actions', 'ReactNode?', 'Header controls.'], ['density', 'default | compact', 'Padding and gap density.']), ['Use Panel for documentation sections and product groups that need a clear heading.']),
  common('tabs', 'Tabs', 'Layout', 'Related content views share a region while the selected tab remains visible.', TabsPreview, snippet('Tabs', '<Tabs label="Project sections" size="compact" items={items} />'), rows(['items', 'readonly TabItem[]', 'Labels, ids, content and disabled state.'], ['value / onChange', 'string? / callback?', 'Controlled selection.'], ['size', 'default | compact', 'Choose the control height for the surrounding density.'], ['listOnly / className', 'boolean? / string?', 'Optional content suppression and styling hook.']), ['Use tabs for distinct content panels. Choose compact or default to match the surrounding density.']),
  common('breadcrumbs', 'Breadcrumbs', 'Navigation', 'A short path that shows where the current page sits in a hierarchy.', BreadcrumbPreview, snippet('Breadcrumbs', '<Breadcrumbs items={items} />'), rows(['items', 'readonly BreadcrumbItem[]', 'Links followed by the current location.'], ['label', 'string?', 'Accessible navigation label.']), ['Keep the trail to meaningful hierarchy levels and make prior locations navigable.']),
  common('pagination', 'Pagination', 'Navigation', 'A compact control for moving through a finite set of pages.', PaginationPreview, snippet('Pagination', '<Pagination page={page} pageCount={5} onPageChange={setPage} />'), rows(['page / pageCount', 'number / number', 'Current page and total.'], ['onPageChange', '(page: number) => void', 'Page selection callback.'], ['disabled / label', 'boolean? / string?', 'Availability and accessible name.']), ['Provide context such as result count near the pagination control.']),
  common('navigation-list', 'Navigation list', 'Navigation', 'A consistent vertical list for page or workspace navigation.', NavigationPreview, snippet('NavigationList', '<NavigationList label="Project navigation" items={items} />'), rows(['label', 'string', 'Accessible navigation name.'], ['items', 'readonly NavigationItem[]', 'Label, href, icon and current state.']), ['Use one current item and keep labels scannable.']),
  common('workflow-steps', 'Workflow steps', 'Navigation', 'A progress-aware navigation list for a multi-step process.', WorkflowPreview, snippet('WorkflowSteps', '<WorkflowSteps label="Project workflow" steps={steps} current="review" onChange={setStep} />'), rows(['steps / current', 'readonly WorkflowStep[] / string', 'Step definitions and current id.'], ['onChange', '(id: string) => void', 'Step selection callback.'], ['orientation', 'horizontal | vertical', 'Layout direction.']), ['Mark completed steps explicitly and keep future disabled steps unavailable.']),
  common('menu', 'Menu', 'Overlays', 'A compact command list anchored to a button.', MenuPreview, snippet('Menu', '<Menu label="More actions" items={items} onSelect={onSelect} />'), rows(['label / items', 'string / readonly MenuItem[]', 'Trigger name and commands.'], ['onSelect', '(id: string) => void', 'Selected command callback.'], ['iconOnly / side', 'boolean? / top | bottom', 'Compact trigger and placement.']), ['Use danger on destructive menu items and keep the trigger label specific.']),
  common('dialog', 'Dialog', 'Overlays', 'A modal surface for decisions that need focus, context or confirmation.', DialogPreview, snippet('Dialog', '<Dialog title="Delete draft" trigger="Delete draft">{children}</Dialog>'), rows(['title / description', 'string / string?', 'Modal heading and context.'], ['trigger', 'string', 'Button label that opens the dialog.'], ['tone', 'neutral | warning | confirmation', 'Semantic heading treatment.'], ['open / onOpenChange', 'boolean? / callback?', 'Controlled visibility.']), ['Keep the primary decision visible and provide a clear way to cancel.']),
  common('drawer', 'Drawer', 'Overlays', 'A modal surface that enters from the edge for secondary navigation or details.', DrawerPreview, snippet('Drawer', '<Drawer title="Documentation" trigger="Open drawer">{children}</Drawer>'), rows(['title / description', 'string / string?', 'Drawer heading and context.'], ['trigger', 'string', 'Button label that opens the drawer.'], ['open / onOpenChange', 'boolean? / callback?', 'Controlled visibility.']), ['Use Drawer for supporting content on small screens; keep the primary task visible behind it.']),
  common('popover', 'Popover', 'Overlays', 'A positioned surface for contextual content or a small set of controls.', PopoverPreview, snippet('Popover', '<Popover label="More information">{children}</Popover>'), rows(['label / children', 'string / ReactNode', 'Trigger label and positioned content.'], ['variant', 'default | field', 'Button or field-like trigger.'], ['open / onOpenChange', 'boolean? / callback?', 'Controlled visibility.'], ['disabled', 'boolean?', 'Prevents opening.']), ['Keep content concise and make the trigger explain what will appear.']),
  common('button-group', 'Button Group', 'Actions', 'Related actions share one aligned control group and can be attached or separated.', ButtonGroupPreview, snippet('ButtonGroup', '<ButtonGroup><Button>Save</Button><Button>Share</Button></ButtonGroup>'), rows(['children', 'ReactNode', 'Buttons or related controls.'], ['attached', 'boolean', 'Joins adjacent controls into one visual group.']), ['Keep one primary action and place supporting actions beside it.']),
  common('compact-button', 'Compact Button', 'Actions', 'A named compact action primitive for dense toolbars and inline controls.', CompactButtonPreview, snippet('CompactButton', '<CompactButton icon="edit">Edit</CompactButton>'), rows(['variant / icon', 'Button variant / IconName?', 'Visual treatment and optional icon.'], ['iconOnly', 'boolean', 'Renders an icon-only control with an accessible label.']), ['Use compact controls in toolbars where the surrounding layout already communicates context.']),
  common('fancy-button', 'Fancy Button', 'Actions', 'A two-line action button for a clear title and supporting description.', FancyButtonPreview, snippet('FancyButton', '<FancyButton size="compact" subtitle="Open workspace">Continue</FancyButton>'), rows(['subtitle', 'string?', 'Supporting line below the action label.'], ['Button props', 'ButtonProps', 'All standard action variants and states.']), ['Keep the subtitle short so the action remains scannable.']),
  common('avatar', 'Avatar', 'Displaying Data', 'An identity marker with initials, image support and an optional status dot.', AvatarPreview, snippet('Avatar', '<Avatar name="Mira Chen" status="online" />'), rows(['name', 'string', 'Accessible name and fallback initials.'], ['src', 'string?', 'Image source.'], ['size / status', 'small | medium | large / online | offline | busy', 'Visual density and presence.']), ['Use a real name for the accessible label even when an image is supplied.']),
  common('avatar-group', 'Avatar Group', 'Displaying Data', 'A compact overlapping collection of avatars with an overflow count.', AvatarGroupPreview, snippet('AvatarGroup', '<AvatarGroup label="Project members" items={members} max={4} />'), rows(['items', 'readonly Avatar[]', 'Names, images and statuses.'], ['max', 'number', 'Visible avatars before the overflow count.'], ['size', 'small | medium | large', 'Group density.']), ['Use the overflow count as a cue to reveal the full member list elsewhere.']),
  common('avatar-group-compact', 'Avatar Group Compact', 'Displaying Data', 'A small-density avatar group for compact rows and metadata.', AvatarGroupCompactPreview, snippet('AvatarGroupCompact', '<AvatarGroupCompact label="Reviewers" items={reviewers} />'), rows(['items / max', 'readonly Avatar[] / number', 'Members and visible count.']), ['Use this in tables and list rows where a full-size group would dominate.']),
  common('badge', 'Badge', 'Displaying Data', 'A compact status or category marker with semantic color and optional icon.', BadgePreview, snippet('Badge', '<Badge tone="success" icon="check">Approved</Badge>'), rows(['children', 'ReactNode', 'Badge label.'], ['tone', 'neutral | accent | success | danger | warning', 'Semantic treatment.'], ['icon', 'IconName?', 'Optional leading icon.']), ['Badge text should remain meaningful without relying on color.']),
  common('banner', 'Banner', 'Displaying Data', 'A persistent message bar for workspace-level status and actions.', BannerPreview, snippet('Banner', '<Banner title="Scheduled maintenance" description="Read-only for five minutes." />'), rows(['title / description', 'string / string?', 'Message content.'], ['tone', 'neutral | accent | success | danger | warning', 'Semantic treatment.'], ['action / onDismiss', 'ReactNode? / callback?', 'Primary action and optional dismissal.']), ['Reserve banners for messages that affect the current workflow or workspace.']),
  common('divider', 'Divider', 'Displaying Data', 'A semantic separator that clarifies related content groups.', DividerPreview, snippet('Divider', '<Divider />'), rows(['className', 'string?', 'Optional layout styling.']), ['Use a divider when whitespace alone does not make the grouping clear.']),
  { ...common('kbd', 'Kbd', 'Displaying Data', 'A keyboard shortcut keycap with shared border, spacing and type treatment.', KbdPreview, snippet('Kbd', '<Kbd>⌘</Kbd><Kbd>K</Kbd>'), rows(['children', 'ReactNode', 'Key label.']), ['Use familiar symbols and pair shortcuts with an action label.']), displayTitle: 'Keyboard Shortcut', overviewTitle: 'Keyboard Shortcut overview' },
  common('status-badge', 'Status Badge', 'Displaying Data', 'A semantic status label that builds on the shared Tag treatment.', TagPreview, snippet('StatusBadge', '<StatusBadge status="pending">Needs attention</StatusBadge>'), rows(['status', 'neutral | pending | success | danger', 'Semantic state and icon.'], ['children', 'ReactNode', 'Visible status label.']), ['Always include a readable state label alongside the visual treatment.']),
  common('notification', 'Notification', 'Feedback', 'A persistent notification with message, action and dismissal affordances.', NotificationPreview, snippet('Notification', '<Notification title="Export complete" actions={<Button>Download</Button>} />'), rows(['title / description', 'string / string?', 'Message content.'], ['tone', 'neutral | accent | success | danger | warning', 'Semantic treatment.'], ['actions / onDismiss', 'ReactNode? / callback?', 'Follow-up and dismissal controls.']), ['Use Notification for durable feedback; use Toast for transient updates.']),
  common('color-picker', 'Color Picker', 'Form', 'An accessible color control with a native swatch, editable hex value and recommended presets.', ColorPickerPreview, snippet('ColorPicker', '<ColorPicker label="Accent color" value={color} onChange={setColor} />'), rows(['label / value', 'string / string', 'Accessible label and current hex value.'], ['onChange', '(value: string) => void', 'Receives a validated six-digit hex color.'], ['presets', 'readonly string[]', 'Quick choices rendered as selectable swatches.']), ['Keep the hex value visible for precise handoff and use presets for common theme colors.']),
  common('digit-input', 'Digit Input', 'Form', 'A segmented numeric input for short verification codes and PINs.', DigitInputPreview, snippet('DigitInput', '<DigitInput label="Verification code" length={4} value={code} onChange={setCode} />'), rows(['length', 'number', 'Number of digit cells.'], ['value / onChange', 'string / callback', 'Controlled code.'], ['disabled / error', 'boolean? / string?', 'Availability and validation.']), ['Keep codes short and use inputMode numeric for mobile keyboards.']),
  common('hint', 'Hint', 'Form', 'Supporting field guidance that can also communicate an inline error.', HintPreview, snippet('Hint', '<Hint>Use lowercase letters and hyphens.</Hint>'), rows(['children', 'ReactNode', 'Supporting message.'], ['tone', 'secondary | danger', 'Guidance or validation treatment.']), ['Hints supplement labels and should remain visible when the field is focused.']),
  common('label', 'Label', 'Form', 'A standalone field label with required marker and optional supporting suffix.', LabelPreview, snippet('Label', '<Label required hint="Optional help text">Project name</Label>'), rows(['children', 'ReactNode', 'Visible field name.'], ['required', 'boolean', 'Adds a required marker.'], ['hint', 'ReactNode?', 'Supporting suffix.']), ['Associate labels with inputs using htmlFor and id.']),
  common('accordion', 'Accordion', 'Layout', 'Expandable content sections that reveal one or more detailed answers in place.', AccordionPreview, snippet('Accordion', '<Accordion label="FAQ" items={items} />'), rows(['label / items', 'string / readonly AccordionItem[]', 'Accessible name and sections.'], ['multiple', 'boolean', 'Allows several sections to stay open.']), ['Use short summaries and preserve the reading order inside each section.']),
  common('segmented-control', 'Segmented Control', 'Layout', 'A single-choice control for switching views or modes.', SegmentedControlPreview, snippet('SegmentedControl', '<SegmentedControl label="View" options={options} />'), rows(['options', 'readonly SegmentOption[]', 'Available choices.'], ['value / onChange', 'string? / callback', 'Controlled selection.'], ['size', 'default | compact', 'Choose compact or default control density.'], ['name / disabled', 'string? / boolean?', 'Form integration and availability.']), ['Use SegmentedControl for a small set of immediate view choices, not page navigation.']),
  common('tab-menu-vertical', 'Tab Menu Vertical', 'Layout', 'A vertical tab rail keeps section navigation visible beside the active content.', TabMenuVerticalPreview, snippet('TabMenuVertical', '<TabMenuVertical label="Settings" items={items} />'), rows(['items', 'readonly TabMenuVerticalItem[]', 'Tab labels and panel content.'], ['value / onChange', 'string? / callback', 'Controlled selection.']), ['Use this layout when the section names benefit from persistent visibility.']),
  common('dot-stepper', 'Dot Stepper', 'Navigation', 'A minimal progress indicator for a short sequence of steps.', DotStepperPreview, snippet('DotStepper', '<DotStepper label="Checkout progress" steps={steps} current={1} />'), rows(['steps', 'readonly string[]', 'Accessible step labels.'], ['current / onChange', 'number / callback', 'Active step and selection callback.']), ['Keep the full step name available to assistive technology through aria-label.']),
  common('vertical-stepper', 'Vertical Stepper', 'Navigation', 'A vertical progress list for onboarding and multi-step workflows.', VerticalStepperPreview, snippet('VerticalStepper', '<VerticalStepper label="Onboarding" current="review" steps={stepsWithDescriptions} onChange={setStep} />'), rows(['steps', 'readonly VerticalStep[]', 'Step labels, descriptions and completion.'], ['current / onChange', 'string? / callback', 'Active step and selection callback.'], ['description', 'string?', 'Supporting context shown beneath a step label.']), ['Use the header-only mode for compact flows and add descriptions when the current step needs context. Connector lines run between marker edges to preserve the sequence.'], undefined, verticalStepperExamples),
  common('command-menu', 'Command Menu', 'Overlays', 'A searchable command dialog with grouped actions and keyboard hints.', CommandMenuPreview, snippet('CommandMenu', '<CommandMenu label="Open command menu" items={items} onSelect={run} />'), rows(['label / items', 'string / readonly MenuItem[]', 'Trigger and commands.'], ['onSelect', '(id: string) => void', 'Selected command callback.'], ['placeholder', 'string?', 'Search field hint.']), ['Keep command labels verb-first and expose a keyboard-friendly path to every action.']),
]

export const componentPageMap = new Map(componentPages.map(page => [page.id, page]))

export type DocumentationInstallPage = { id: string; title: string; source: string }

export function DocumentationInstallation({ page }: { page?: DocumentationInstallPage }) {
  const [manager, setManager] = useState('npm')
  const command = manager === 'pnpm' ? 'pnpm add' : manager === 'yarn' ? 'yarn add' : 'npm install'
  if (!page) return <Stack gap={6} className="docs-installation-group">
    <CodeExample headingLevel={3} title="1. Build and pack the library" filename="terminal · design-system repository" source={'npm run build:atomic-library\nnpm pack ./dist-atomic-library'} />
    <CodeExample headingLevel={3} title="2. Install the local package" description="Use the filename printed by npm pack in your consuming application." filename="terminal · consuming application" source={`${command} ./vendor/brutalist-design-system-0.1.0-atomic.0.tgz`} controls={<Tabs label="Package manager" size="compact" value={manager} onChange={setManager} options={[{ value: 'npm', label: 'npm' }, { value: 'pnpm', label: 'pnpm' }, { value: 'yarn', label: 'yarn' }]} />} />
    <CodeExample headingLevel={3} title="3. Provide the shared foundation" description="Import the stylesheet once and wrap the application with AtomsRoot." filename="App.tsx" source={"import { AtomsRoot } from 'brutalist-design-system'\nimport 'brutalist-design-system/styles.css'\n\nexport default function App() {\n  return <AtomsRoot>Your application</AtomsRoot>\n}"} />
  </Stack>
  return <Stack gap={6} className="docs-component-installation">
    <Text variant="small" tone="secondary">{page.title} is included in the shared package. Install the library once from Getting Started, then use the public component export below.</Text>
    <CodeExample headingLevel={3} title={`1. Add ${page.title} to your application`} description={`Import ${page.title} from the public package and use it in your application.`} filename={`${page.id}.tsx`} source={page.source} />
  </Stack>
}
