import { useState, type ComponentType, type ReactNode } from 'react'
import { Container, Heading, Icon, Inline, Stack, Surface, Text } from '../../atoms'
import {
  Alert, AttachmentArea, Breadcrumbs, Button, Checkbox, Combobox, DatePicker, Dialog, Drawer,
  EmptyState, FileDropzone, FileList, Form, FormActions, InlineConfirmation, InlineText,
  Menu, MultiSelect, NavigationList, NumberStepper, Pagination, Panel, PasswordField,
  Popover, ProgressBar, ProgressRing, RadioGroup, RangeSlider, Rating, SearchField, Select,
  SegmentedControl, Skeleton, Slider, Spinner, StatusBadge, Table, Tabs, Tag, TextAction,
  TextArea, TextField, Toast, Toggle, Tooltip, WorkflowSteps,
  type FileItem,
} from '../../components'
import { CodeExample } from '../../ui-blocks/CodeExample'

export type ComponentReferenceRow = { name: string; value: string; purpose: string }
export type ComponentExample = { id: string; title: string; description?: string; source: string; preview: ComponentType }
export type ComponentSpec = {
  id: string
  title: string
  category: string
  description: string
  source: string
  preview: ComponentType
  example?: { title: string; description: string; preview: ComponentType }
  examples?: ComponentExample[]
  composition?: ComponentExample
  reference: ComponentReferenceRow[]
  notes: string[]
}

const rows = (...items: [string, string, string][]): ComponentReferenceRow[] => items.map(([name, value, purpose]) => ({ name, value, purpose }))
const snippet = (imports: string, body: string) => `import { ${imports} } from 'brutalist-design-system'\n\nexport function Example() {\n  return ${body}\n}`

function ButtonPreview() { const [result, setResult] = useState(''); return <Stack gap={3}><Button variant="primary" onClick={() => setResult('Button activated')}>Button</Button>{result && <Text role="status" variant="small">{result}</Text>}</Stack> }
function ButtonPrimaryPreview() { return <Button variant="primary">Get started</Button> }
function ButtonNeutralPreview() { return <Button>Learn more</Button> }
function ButtonErrorPreview() { return <Button variant="danger">Try again</Button> }
function ButtonSizePreview() { return <Inline gap={3} className="docs-button-size-row">{(['medium', 'small', 'xsmall', 'xxsmall'] as const).map(size => <Button key={size} size={size} variant="primary">{size === 'medium' ? 'Medium' : size === 'xsmall' ? 'Xsmall' : size === 'xxsmall' ? 'Xxsmall' : 'Small'}</Button>)}</Inline> }
function ButtonDisabledPreview() { return <Inline gap={3}><Button variant="primary" disabled>Disabled</Button><Button disabled>Disabled</Button><Button variant="danger" disabled>Disabled</Button></Inline> }
function ButtonIconPreview() { return <Inline gap={3}><Button variant="primary" icon="plus">Create</Button><Button icon="arrowRight" iconPosition="end">Continue</Button><Button variant="danger" icon="delete">Delete</Button></Inline> }
function ButtonFullWidthPreview() { return <Button className="docs-button-full-width" variant="primary">Learn more</Button> }
function ButtonAsChildPreview() { return <TextAction href="#reference">As link</TextAction> }
function ButtonCompositionPreview() { function ActionButton({ children }: { children: ReactNode }) { return <Button variant="primary" size="compact">{children}</Button> } return <ActionButton>Save changes</ActionButton> }
function TextActionPreview() { return <Inline gap={4}><TextAction href="#component-text-action">Read the guide</TextAction><TextAction onClick={() => undefined}>Run action</TextAction></Inline> }
function FormActionsPreview() { return <Form label="Example form" onSubmit={event => event.preventDefault()}><TextField label="Project name" defaultValue="Oslo launch" /><FormActions onCancel={() => undefined} message="Actions belong at the end of a form." /></Form> }
function InlineConfirmationPreview() { const [confirmed, setConfirmed] = useState(false); return <Stack gap={3}><InlineConfirmation label="Delete draft" question="Delete this draft?" description="This demo keeps the action inline until you confirm." onConfirm={() => setConfirmed(true)} />{confirmed && <Text role="status" variant="small">Draft deleted.</Text>}</Stack> }
function TablePreview() { const data = [{ id: 'brief', name: 'Campaign brief', owner: 'Mira' }, { id: 'review', name: 'Creative review', owner: 'Jonas' }]; return <Table label="Projects" rows={data} rowKey={row => row.id} columns={[{ id: 'name', header: 'Project', render: row => <Text>{row.name}</Text>, sortable: true }, { id: 'owner', header: 'Owner', render: row => <Text variant="small">{row.owner}</Text> }]} /> }
function TagPreview() { return <Inline gap={2}><Tag tone="accent" icon="Sparkles">In review</Tag><Tag tone="success" status="success">Approved</Tag><StatusBadge status="pending">Needs attention</StatusBadge></Inline> }
function ProgressPreview() { return <Stack gap={6}><ProgressBar label="Export progress" value={68} /><Inline gap={8}><ProgressRing label="Storage" value={72} description="72% used" /><ProgressRing label="Quality" value={96} /></Inline></Stack> }
function RatingPreview() { const [value, setValue] = useState(4); return <Rating label="Rate this example" value={value} onChange={setValue} /> }
function AlertPreview() { return <Stack gap={3}><Alert title="Saved" description="Your changes are ready for review." tone="success" /><Alert title="Check the fields" description="Color is paired with a message and icon." tone="danger" /></Stack> }
function ToastPreview() { const [visible, setVisible] = useState(true); return visible ? <Toast title="Draft saved" description="You can continue editing." tone="success" onDismiss={() => setVisible(false)} /> : <Button onClick={() => setVisible(true)}>Show toast</Button> }
function FeedbackPreview() { return <Stack gap={4}><Tooltip label="Hover for help" content="Tooltips explain an unfamiliar control." /><Inline gap={6}><Spinner label="Loading preview" /><Skeleton label="Loading rows" lines={2} /></Inline><EmptyState title="No campaigns" description="Create one to start planning." action={<Button variant="primary">Create campaign</Button>} /></Stack> }
function FormPreview() { return <Form label="Campaign settings"><TextField label="Campaign name" defaultValue="Nordic spring" /><TextArea label="Description" defaultValue="A short campaign description." /><Checkbox label="Include animated formats" defaultChecked /><Toggle label="Publish automatically" /><FormActions /></Form> }
function TextFieldPreview() { const [value, setValue] = useState('Nordic spring'); return <Stack gap={4}><TextField label="Campaign title" value={value} onChange={event => setValue(event.target.value)} instructions="Keep it short and descriptive." /><TextField label="Read-only ID" value="campaign-001" readOnly /></Stack> }
function SearchPreview() { const [value, setValue] = useState(''); return <SearchField label="Search campaigns" placeholder="Search by name" value={value} onChange={setValue} /> }
function PasswordPreview() { return <PasswordField label="Workspace password" defaultValue="secret" instructions="Use at least twelve characters." /> }
function TextAreaPreview() { return <TextArea label="Campaign brief" rows={4} placeholder="Describe the campaign" instructions="Markdown is supported." /> }
function CheckboxPreview() { const [mixed, setMixed] = useState(true); return <Stack gap={3}><Checkbox label="Select all formats" indeterminate={mixed} checked={!mixed} onChange={event => setMixed(!event.target.checked)} /><Checkbox label="Include motion" defaultChecked /></Stack> }
function RadioPreview() { const [value, setValue] = useState('square'); return <RadioGroup label="Export format" value={value} onChange={setValue} options={[{ value: 'square', label: 'Square' }, { value: 'portrait', label: 'Portrait' }, { value: 'landscape', label: 'Landscape', disabled: true }]} /> }
function TogglePreview() { const [checked, setChecked] = useState(false); return <Toggle label="Publish automatically" checked={checked} onChange={event => setChecked(event.target.checked)} instructions="Turn this on to publish after approval." /> }
const selectOptions = [{ value: 'brief', label: 'Campaign brief' }, { value: 'review', label: 'Creative review' }, { value: 'delivery', label: 'Delivery', disabled: true }]
function DropdownPreview() { const [select, setSelect] = useState('brief'); const [combo, setCombo] = useState('brief'); const [multi, setMulti] = useState<string[]>(['review']); return <Stack gap={4}><Select label="Select a project" options={selectOptions} value={select} onValueChange={setSelect} /><Combobox label="Find a project" options={selectOptions} value={combo} onChange={setCombo} /><MultiSelect label="Filter projects" options={selectOptions} value={multi} onChange={setMulti} /></Stack> }
function DatePickerPreview() { const [date, setDate] = useState('2026-09-15'); return <DatePicker label="Launch date" value={date} onValueChange={setDate} /> }
function NumberStepperPreview() { const [value, setValue] = useState(3); return <NumberStepper label="Variants" value={value} onChange={setValue} min={1} max={10} /> }
function SliderPreview() { const [value, setValue] = useState(64); return <Slider label="Quality" value={value} onChange={setValue} formatValue={value => `${value}%`} /> }
function RangeSliderPreview() { const [value, setValue] = useState<[number, number]>([20, 80]); return <RangeSlider label="Budget range" value={value} onChange={setValue} lowerLabel="Minimum" upperLabel="Maximum" /> }
function FilesPreview() { const files: FileItem[] = [{ id: 'brief', name: 'campaign-brief.pdf', size: 24000 }, { id: 'copy', name: 'headline.md', size: 3400 }]; return <Stack gap={4}><FileDropzone label="Upload creative files" multiple onFiles={() => undefined} accept=".pdf,.md" /><FileList files={files} onRemove={() => undefined} /></Stack> }
function AttachmentPreview() { return <AttachmentArea label="Campaign attachments" onFiles={() => undefined}><TextArea label="Add a note" placeholder="Drop files or write a note" embedded /></AttachmentArea> }
function InlineTextPreview() { const [value, setValue] = useState('Editable campaign title'); return <InlineText label="Campaign title" value={value} onSave={next => setValue(next)} /> }
function PanelPreview() { return <Panel title="Campaign brief" description="Panel groups a heading, supporting copy and content."><Text>Content stays on a shared surface.</Text></Panel> }
function TabsPreview() { const [tab, setTab] = useState('overview'); return <Stack gap={4}><Tabs label="Campaign sections" size="compact" value={tab} onChange={setTab} items={[{ id: 'overview', label: 'Overview', content: <Text>Overview content.</Text> }, { id: 'activity', label: 'Activity', content: <Text>Activity content.</Text> }]} /><SegmentedControl label="View" size="compact" options={[{ value: 'grid', label: 'Grid' }, { value: 'list', label: 'List' }]} /></Stack> }
function BreadcrumbPreview() { return <Breadcrumbs items={[{ label: 'Projects', href: '#' }, { label: 'Nordic spring', href: '#' }, { label: 'Brief' }]} /> }
function PaginationPreview() { const [page, setPage] = useState(2); return <Pagination page={page} pageCount={5} onPageChange={setPage} /> }
function NavigationPreview() { return <NavigationList label="Project navigation" items={[{ id: 'overview', label: 'Overview', href: '#', icon: 'LayoutDashboard', current: true }, { id: 'settings', label: 'Settings', href: '#', icon: 'settings' }]} /> }
function WorkflowPreview() { const [current, setCurrent] = useState('review'); return <WorkflowSteps label="Campaign workflow" current={current} onChange={setCurrent} steps={[{ id: 'brief', label: 'Brief', complete: true }, { id: 'review', label: 'Review', description: 'Check copy' }, { id: 'publish', label: 'Publish', disabled: true }]} /> }
function MenuPreview() { const [result, setResult] = useState(''); return <Stack gap={3}><Menu label="More actions" items={[{ id: 'edit', label: 'Edit', icon: 'edit' }, { id: 'duplicate', label: 'Duplicate', icon: 'copy' }, { id: 'delete', label: 'Delete', danger: true }]} onSelect={setResult} />{result && <Text role="status" variant="small">Selected: {result}</Text>}</Stack> }
function DialogPreview() { return <Dialog title="Delete draft" description="This dialog asks for confirmation before the action." trigger="Delete draft"><Inline gap={3}><Button variant="danger" onClick={() => undefined}>Delete</Button><Button>Cancel</Button></Inline></Dialog> }
function DrawerPreview() { return <Drawer title="Documentation" description="A drawer keeps secondary navigation available on small screens." trigger="Open drawer"><NavigationList label="Drawer links" items={[{ id: 'overview', label: 'Overview', href: '#' }, { id: 'settings', label: 'Settings', href: '#' }]} /></Drawer> }
function PopoverPreview() { return <Popover label="More information"><Stack gap={2}><Text variant="small">Popover content is positioned by the shared overlay primitive.</Text><Button size="compact">Continue</Button></Stack></Popover> }

const buttonExamples: ComponentExample[] = [
  { id: 'primary', title: 'Primary (Default)', description: 'Use the accent action for the main path through a view.', source: snippet('Button', '<Button variant="primary">Get started</Button>'), preview: ButtonPrimaryPreview },
  { id: 'neutral', title: 'Neutral', description: 'Use the neutral action for supporting or secondary work.', source: snippet('Button', '<Button>Learn more</Button>'), preview: ButtonNeutralPreview },
  { id: 'error', title: 'Error', description: 'Use the danger treatment for destructive or recovery actions.', source: snippet('Button', '<Button variant="danger">Try again</Button>'), preview: ButtonErrorPreview },
  { id: 'size', title: 'Size', description: 'Choose a named size to match the surrounding density.', source: snippet('Button', '<Inline gap={3}>\n  <Button size="medium">Medium</Button>\n  <Button size="small">Small</Button>\n  <Button size="xsmall">Xsmall</Button>\n  <Button size="xxsmall">Xxsmall</Button>\n</Inline>'), preview: ButtonSizePreview },
  { id: 'disabled', title: 'Disabled', description: 'Disabled actions remain visible while preventing activation.', source: snippet('Button', '<Button variant="primary" disabled>Disabled</Button>'), preview: ButtonDisabledPreview },
  { id: 'with-icon', title: 'With Icon', description: 'Pair a concise verb with an icon when it improves recognition.', source: snippet('Button', '<Button variant="primary" icon="plus">Create</Button>'), preview: ButtonIconPreview },
  { id: 'full-width', title: 'Full Width', description: 'Use the full-width composition when the action owns the available row.', source: snippet('Button', '<Button className="docs-button-full-width" variant="primary">Learn more</Button>'), preview: ButtonFullWidthPreview },
  { id: 'as-child', title: 'asChild', description: 'Use a text action when the same visual action should navigate as a link.', source: snippet('TextAction', '<TextAction href="/guide">As link</TextAction>'), preview: ButtonAsChildPreview },
]
const buttonComposition: ComponentExample = { id: 'composition', title: 'Button composition', description: 'Create a small wrapper when an action has a consistent product-specific meaning.', source: "import { Button } from 'brutalist-design-system'\n\nfunction SaveButton() {\n  return <Button variant=\"primary\" size=\"compact\">Save changes</Button>\n}\n\nexport function Toolbar() {\n  return <SaveButton />\n}" , preview: ButtonCompositionPreview }

const common = (id: string, title: string, category: string, description: string, preview: ComponentType, source: string, reference: ComponentReferenceRow[], notes: string[], example?: ComponentSpec['example'], examples?: ComponentExample[], composition?: ComponentExample): ComponentSpec => ({ id, title, category, description, preview, source, reference, notes, example, examples, composition })

export const componentPages: ComponentSpec[] = [
  common('button', 'Button', 'Actions', 'Buttons trigger an action and communicate their importance through a shared variant, size and state model.', ButtonPreview, snippet('Button', '<Button variant="primary" icon="plus">Create campaign</Button>'), rows(['variant', 'primary | secondary | danger | quiet', 'Visual importance; defaults to secondary.'], ['size', 'default | compact | medium | small | xsmall | xxsmall', 'Named sizes map to our shared control density tokens.'], ['icon / iconPosition', 'IconName / start | end', 'Optional leading or trailing icon.'], ['busy / disabled', 'boolean', 'Busy blocks repeat activation and disabled prevents input.']), ['Prefer a verb that describes the result. Keep one primary action in a group.', 'Icon-only buttons require an accessible aria-label.'], undefined, buttonExamples, buttonComposition),
  common('text-action', 'Text action', 'Actions', 'A low-emphasis action that keeps the surrounding sentence or list compact.', TextActionPreview, snippet('TextAction', '<TextAction href="/guide">Read the guide</TextAction>'), rows(['href', 'string | undefined', 'Renders a link when provided; otherwise a button.'], ['disabled', 'boolean', 'Prevents the button action.']), ['Use this for inline navigation or a secondary action.']),
  common('form-actions', 'Form actions', 'Actions', 'A consistent submit and cancel row for forms, including busy and status feedback.', FormActionsPreview, snippet('Form, FormActions, TextField', '<FormActions onCancel={onCancel} submitLabel="Save" />'), rows(['submitLabel / cancelLabel', 'string', 'Action labels; defaults Save and Cancel.'], ['busy / disabled', 'boolean', 'Busy changes the submit button state.'], ['message', 'ReactNode', 'Optional status text below the buttons.']), ['Place FormActions as the last child of Form.']),
  common('inline-confirmation', 'Inline confirmation', 'Actions', 'A compact confirmation pattern that reveals the question in place of a separate dialog.', InlineConfirmationPreview, snippet('InlineConfirmation', '<InlineConfirmation label="Delete draft" question="Delete this draft?" onConfirm={removeDraft} />'), rows(['label / question', 'string', 'Trigger label and confirmation prompt.'], ['onConfirm', '() => void | Promise<void>', 'Runs after confirmation.'], ['description / disabled', 'string? / boolean?', 'Supporting copy and disabled state.']), ['Use Dialog when the decision needs more context or an explicit cancel action.']),
  common('table', 'Table', 'Displaying Data', 'Tables expose structured rows with optional sorting and an accessible scroll region.', TablePreview, snippet('Table', '<Table label="Projects" rows={rows} rowKey={row => row.id} columns={columns} />'), rows(['label / rows / rowKey', 'string / readonly T[] / (row) => string', 'Accessible name and stable row identity.'], ['columns', 'readonly TableColumn<T>[]', 'Headers and cell renderers.'], ['sort / onSort', 'TableSort? / callback?', 'Optional controlled sorting.'], ['emptyMessage', 'string', 'Message for an empty table.']), ['Keep column headers short and provide a meaningful empty state.']),
  common('tag', 'Tag / Status badge', 'Displaying Data', 'Tags label an item or status at a glance, with optional icon and removal affordance.', TagPreview, snippet('Tag, StatusBadge', '<Tag tone="accent">In review</Tag>'), rows(['tone', 'neutral | accent | success | danger', 'Color treatment; always pair status with text.'], ['status', 'TagStatus?', 'Status icon/state when supported.'], ['onRemove / removeLabel', 'callback? / string?', 'Optional removal action.'], ['showIcon', 'boolean', 'StatusBadge icon visibility.']), ['Use StatusBadge when the value describes a state; use Tag for a category or filter.']),
  common('progress-bar', 'Progress bar', 'Displaying Data', 'A horizontal indicator for a measurable task or value range.', ProgressPreview, snippet('ProgressBar', '<ProgressBar label="Export progress" value={68} />'), rows(['label', 'string', 'Accessible name.'], ['value / max', 'number? / number', 'Current and maximum values.'], ['showValue', 'boolean', 'Whether the percentage is visible.']), ['Keep the label visible when progress is important to understanding the task.']),
  common('progress-ring', 'Progress ring', 'Displaying Data', 'A compact circular indicator for capacity or task completion.', ProgressPreview, snippet('ProgressRing', '<ProgressRing label="Storage" value={72} description="72% used" />'), rows(['label / value / max', 'string / number / number', 'Accessible name and range.'], ['description', 'string?', 'Supporting text beside the ring.']), ['Use a ring when the value belongs to a compact summary; use a bar for a long-running task.']),
  common('rating', 'Rating', 'Displaying Data', 'A keyboard-accessible star rating with a controlled numeric value.', RatingPreview, snippet('Rating', '<Rating label="Rate this example" value={4} onChange={setValue} />'), rows(['label / value / max', 'string / number / number', 'Accessible name, selected value and number of stars.'], ['onChange', '(value: number) => void', 'Receives the selected value.'], ['disabled', 'boolean?', 'Prevents changes.']), ['Include a text label; the stars are a visual representation of the value.']),
  common('alert', 'Alert', 'Feedback', 'An inline message for a state that belongs in the current content flow.', AlertPreview, snippet('Alert', '<Alert title="Saved" description="Your changes are ready." tone="success" />'), rows(['title / description', 'string / ReactNode?', 'Primary message and supporting detail.'], ['tone', 'neutral | success | danger', 'Semantic treatment.'], ['showIcon / announce', 'boolean', 'Icon visibility and live announcement.'], ['action', 'ReactNode?', 'Optional action control.']), ['Use announce for updates that need immediate assistive-technology feedback.']),
  common('toast', 'Toast', 'Feedback', 'A transient status message with a consistent dismiss action.', ToastPreview, snippet('Toast', '<Toast title="Draft saved" onDismiss={hideToast} />'), rows(['title / description', 'string / ReactNode?', 'Message content.'], ['tone', 'neutral | success | danger', 'Semantic treatment.'], ['onDismiss', '() => void', 'Dismisses the toast.']), ['Keep the message short and do not hide essential information only in a toast.']),
  common('tooltip', 'Tooltip', 'Feedback', 'A short explanation shown on hover or focus for an unfamiliar control.', FeedbackPreview, snippet('Tooltip', '<Tooltip label="Hover for help" content="Explain this setting." />'), rows(['label', 'string', 'Trigger text.'], ['content', 'string', 'Tooltip explanation.']), ['Tooltips supplement labels; they should not carry required instructions alone.']),
  common('spinner', 'Spinner', 'Feedback', 'A compact live indicator for work that has not completed.', FeedbackPreview, snippet('Spinner', '<Spinner label="Loading preview" />'), rows(['label', 'string', 'Accessible live status.']), ['Use a specific label such as “Saving campaign” instead of “Loading” when possible.']),
  common('skeleton', 'Skeleton', 'Feedback', 'Placeholder lines preserve layout while content is loading.', FeedbackPreview, snippet('Skeleton', '<Skeleton label="Loading rows" lines={3} />'), rows(['label', 'string?', 'Accessible status label.'], ['lines', 'number · 1–10', 'Number of placeholder lines.']), ['Match the expected content shape and replace it when data arrives.']),
  common('empty-state', 'Empty state', 'Feedback', 'A quiet surface that explains an empty collection and offers a next step.', FeedbackPreview, snippet('EmptyState', '<EmptyState title="No campaigns" description="Create one to start." action={<Button>Create</Button>} />'), rows(['title', 'string', 'Primary explanation.'], ['description / action', 'string? / ReactNode?', 'Supporting guidance and optional next action.']), ['Explain why the space is empty and what the user can do next.']),
  common('form', 'Form', 'Form', 'A labeled vertical form wrapper that uses the shared spacing scale.', FormPreview, snippet('Form', '<Form label="Campaign settings">{children}</Form>'), rows(['label', 'string', 'Accessible form name.'], ['native form props', 'FormHTMLAttributes', 'Submit, method and native form behavior.']), ['Keep field validation close to its field and finish with FormActions.']),
  common('text-field', 'Text field', 'Form', 'A single-line input with instructions, validation and native input behavior.', TextFieldPreview, snippet('TextField', '<TextField label="Campaign title" value={title} onChange={onChange} />'), rows(['label', 'ReactNode', 'Visible and accessible field label.'], ['instructions / error', 'ReactNode?', 'Supporting and invalid-state messages.'], ['width', 'full | content', 'Sizing; defaults to full for text.'], ['trailing', 'ReactNode?', 'Trailing content inside the field.']), ['Use readOnly for values users can copy but not edit; use disabled when unavailable.']),
  common('search-field', 'Search field', 'Form', 'A text field with a clear affordance and a value callback for filtering.', SearchPreview, snippet('SearchField', '<SearchField label="Search campaigns" value={query} onChange={setQuery} />'), rows(['label / value', 'string / string', 'Accessible label and controlled value.'], ['onChange', '(value: string) => void', 'Called with the new query.'], ['autoFocus / placeholder', 'boolean? / string?', 'Initial focus and hint.']), ['Keep search state in the owning screen so navigation and results stay synchronized.']),
  common('password-field', 'Password field', 'Form', 'A password input that preserves the TextField label and validation contract.', PasswordPreview, snippet('PasswordField', '<PasswordField label="Workspace password" />'), rows(['label', 'string', 'Visible and accessible label.'], ['native input props', 'InputHTMLAttributes', 'Autocomplete, name, required and validation.']), ['Set an appropriate autocomplete value when used for authentication.']),
  common('textarea', 'Text area', 'Form', 'A multiline field for descriptions, notes and longer text.', TextAreaPreview, snippet('TextArea', '<TextArea label="Campaign brief" rows={4} />'), rows(['label / rows', 'ReactNode / number', 'Label and visible height.'], ['embedded', 'boolean', 'Removes outer field chrome for composition.'], ['instructions / error', 'ReactNode?', 'Supporting and invalid-state messages.']), ['Use a concise label and give longer fields an instruction when format matters.']),
  common('checkbox', 'Checkbox', 'Form', 'A binary or mixed selection control for independent options.', CheckboxPreview, snippet('Checkbox', '<Checkbox label="Include motion" checked={included} onChange={onChange} />'), rows(['label', 'ReactNode', 'Visible and accessible label.'], ['checked / indeterminate', 'boolean', 'Controlled value and mixed state.'], ['instructions / error', 'ReactNode?', 'Supporting and invalid-state messages.']), ['Use indeterminate for a parent selection whose children are mixed.']),
  common('radio-group', 'Radio group', 'Form', 'A labeled set of mutually exclusive options with optional custom text.', RadioPreview, snippet('RadioGroup', '<RadioGroup label="Export format" options={options} value={value} onChange={setValue} />'), rows(['label / options', 'string / readonly RadioOption[]', 'Group label and choices.'], ['value / onChange', 'string? / callback', 'Controlled selected option.'], ['customOption', 'object?', 'Optional text-backed choice.'], ['error / disabled', 'ReactNode? / boolean', 'Validation and availability.']), ['Use RadioGroup when users should see all mutually exclusive options at once.']),
  common('toggle', 'Toggle', 'Form', 'A binary setting control for an immediate preference or mode.', TogglePreview, snippet('Toggle', '<Toggle label="Publish automatically" checked={enabled} onChange={onChange} />'), rows(['label', 'ReactNode', 'Visible and accessible label.'], ['checked / defaultChecked', 'boolean?', 'Controlled or initial state.'], ['instructions / error', 'ReactNode?', 'Supporting and invalid-state messages.']), ['Use a checkbox when the change is part of a form submission; use Toggle for an immediate setting.']),
  common('dropdowns', 'Select / Combobox / MultiSelect', 'Form', 'Three related controls for choosing one option, searching options or choosing several.', DropdownPreview, snippet('Select, Combobox, MultiSelect', '<Select label="Project" options={options} value={value} onValueChange={setValue} />'), rows(['Select.options', 'readonly SelectOption[]', 'Options for the single-choice field.'], ['Combobox.onChange', '(value: string) => void', 'Selected option callback.'], ['MultiSelect.value', 'readonly string[]', 'Selected values.'], ['disabled / name', 'boolean? / string?', 'Availability and native form name.']), ['Select is best for a short known list; Combobox helps users search; MultiSelect exposes independent choices.']),
  common('date-picker', 'Date picker', 'Form', 'A date input that keeps the shared field label and validation behavior.', DatePickerPreview, snippet('DatePicker', '<DatePicker label="Launch date" value={date} onValueChange={setDate} />'), rows(['label / value', 'string / string?', 'Label and ISO date value.'], ['min / max', 'string?', 'Allowed date bounds.'], ['onValueChange', '(value: string) => void', 'Date callback.']), ['Store dates as ISO strings and set min/max when the domain has clear limits.']),
  common('number-stepper', 'Number stepper', 'Form', 'A numeric field with increment and decrement controls.', NumberStepperPreview, snippet('NumberStepper', '<NumberStepper label="Variants" value={value} onChange={setValue} min={1} max={10} />'), rows(['value / onChange', 'number / callback', 'Controlled numeric value.'], ['min / max / step', 'number?', 'Range and increment.'], ['instructions / disabled', 'ReactNode? / boolean', 'Supporting copy and availability.']), ['Show units in the label or instructions so the number has clear meaning.']),
  common('slider', 'Slider', 'Form', 'A keyboard-accessible range input for continuous or stepped values.', SliderPreview, snippet('Slider', '<Slider label="Quality" value={64} onChange={setValue} formatValue={formatValue} />'), rows(['value / onChange', 'number / callback', 'Controlled numeric value.'], ['min / max / step', 'number?', 'Range and increment.'], ['formatValue', '(value: number) => string', 'Visible value formatter.']), ['Always provide a label and a useful formatter when the number needs units.']),
  common('range-slider', 'Range slider', 'Form', 'Two coordinated sliders for selecting a lower and upper bound.', RangeSliderPreview, snippet('RangeSlider', '<RangeSlider label="Budget range" value={[20, 80]} onChange={setValue} />'), rows(['value / onChange', '[number, number] / callback', 'Lower and upper values.'], ['lowerLabel / upperLabel', 'string', 'Names for both handles.'], ['names', '[string, string]?', 'Optional native field names.']), ['Keep lower and upper values ordered and give each handle a meaningful label.']),
  common('file-dropzone', 'File dropzone', 'Form', 'A file picker and drop target with type, size and upload states.', FilesPreview, snippet('FileDropzone', '<FileDropzone label="Upload creative files" multiple onFiles={onFiles} />'), rows(['label / onFiles', 'string / (files: File[]) => void', 'Prompt and accepted files callback.'], ['accept / multiple', 'string? / boolean?', 'File types and count.'], ['state / progress', 'idle | uploading | success | error / number', 'Upload feedback.'], ['maxSize / onRetry', 'number? / callback?', 'Per-file limit and retry action.']), ['Tell users which formats and limits are accepted before they choose a file.']),
  common('file-list', 'File list', 'Form', 'A compact list of selected files with optional remove actions.', FilesPreview, snippet('FileList', '<FileList files={files} onRemove={removeFile} />'), rows(['files', 'readonly FileItem[]', 'Stable id, name and optional size.'], ['onRemove', '(id: string) => void', 'Optional remove callback.'], ['disabled', 'boolean?', 'Disables remove controls.']), ['Keep the original filename visible and preserve a stable id for each item.']),
  common('attachment-area', 'Attachment area', 'Form', 'A composed input surface for notes with an optional attachment affordance.', AttachmentPreview, snippet('AttachmentArea', '<AttachmentArea label="Attachments" onFiles={onFiles}>{children}</AttachmentArea>'), rows(['label / children', 'string / ReactNode', 'Group name and composed content.'], ['actions', 'ReactNode?', 'Additional toolbar actions.'], ['onFiles / accept / maxSize', 'callback? / string? / number?', 'Attachment behavior and limits.']), ['Use this when a note and its attachments are one coherent task.']),
  common('inline-text', 'Inline text', 'Form', 'Text that becomes an edit field in place, with save, cancel and async feedback.', InlineTextPreview, snippet('InlineText', '<InlineText label="Campaign title" value={title} onSave={saveTitle} />'), rows(['label / value', 'string / string', 'Accessible label and displayed text.'], ['onSave', '(value, sourceKey?) => void | Promise', 'Save callback.'], ['variant / readOnly', 'TypeRole / boolean?', 'Visual role and editability.'], ['required / maxLength', 'boolean? / number?', 'Validation constraints.']), ['Use a short value and keep the save operation resilient to async failure.']),
  common('panel', 'Panel', 'Layout', 'A framed grouping surface with a heading, supporting copy, filters and actions.', PanelPreview, snippet('Panel', '<Panel title="Campaign brief" description="Related content.">{children}</Panel>'), rows(['title / description', 'string / ReactNode?', 'Heading and supporting copy.'], ['variant', 'default | split', 'Split separates header from content.'], ['filters / actions', 'ReactNode?', 'Header controls.'], ['density', 'default | compact', 'Padding and gap density.']), ['Use Panel for documentation sections and product groups that need a clear heading.']),
  common('tabs', 'Tabs / Segmented control', 'Layout', 'Related views share a region while the selected tab or segment remains visible.', TabsPreview, snippet('Tabs, SegmentedControl', '<Tabs label="Campaign sections" size="compact" items={items} />'), rows(['Tabs.items', 'readonly TabItem[]', 'Labels, ids, content and disabled state.'], ['Tabs.value / onChange', 'string? / callback?', 'Controlled selection.'], ['Tabs.size / SegmentedControl.size', 'default | compact', 'Use compact for the 44px control height.'], ['SegmentedControl.options', 'readonly SegmentOption[]', 'Compact choice options.'], ['orientation / disabled', 'native props / boolean?', 'Composition and availability.']), ['Use tabs for distinct content panels; use SegmentedControl for a compact choice between views.']),
  common('breadcrumbs', 'Breadcrumbs', 'Navigation', 'A short path that shows where the current page sits in a hierarchy.', BreadcrumbPreview, snippet('Breadcrumbs', '<Breadcrumbs items={items} />'), rows(['items', 'readonly BreadcrumbItem[]', 'Links followed by the current location.'], ['label', 'string?', 'Accessible navigation label.']), ['Keep the trail to meaningful hierarchy levels and make prior locations navigable.']),
  common('pagination', 'Pagination', 'Navigation', 'A compact control for moving through a finite set of pages.', PaginationPreview, snippet('Pagination', '<Pagination page={page} pageCount={5} onPageChange={setPage} />'), rows(['page / pageCount', 'number / number', 'Current page and total.'], ['onPageChange', '(page: number) => void', 'Page selection callback.'], ['disabled / label', 'boolean? / string?', 'Availability and accessible name.']), ['Provide context such as result count near the pagination control.']),
  common('navigation-list', 'Navigation list', 'Navigation', 'A consistent vertical list for page or workspace navigation.', NavigationPreview, snippet('NavigationList', '<NavigationList label="Project navigation" items={items} />'), rows(['label', 'string', 'Accessible navigation name.'], ['items', 'readonly NavigationItem[]', 'Label, href, icon and current state.']), ['Use one current item and keep labels scannable.']),
  common('workflow-steps', 'Workflow steps', 'Navigation', 'A progress-aware navigation list for a multi-step process.', WorkflowPreview, snippet('WorkflowSteps', '<WorkflowSteps label="Campaign workflow" steps={steps} current="review" onChange={setStep} />'), rows(['steps / current', 'readonly WorkflowStep[] / string', 'Step definitions and current id.'], ['onChange', '(id: string) => void', 'Step selection callback.'], ['orientation', 'horizontal | vertical', 'Layout direction.']), ['Mark completed steps explicitly and keep future disabled steps unavailable.']),
  common('menu', 'Menu', 'Overlays', 'A compact command list anchored to a button.', MenuPreview, snippet('Menu', '<Menu label="More actions" items={items} onSelect={onSelect} />'), rows(['label / items', 'string / readonly MenuItem[]', 'Trigger name and commands.'], ['onSelect', '(id: string) => void', 'Selected command callback.'], ['iconOnly / side', 'boolean? / top | bottom', 'Compact trigger and placement.']), ['Use danger on destructive menu items and keep the trigger label specific.']),
  common('dialog', 'Dialog', 'Overlays', 'A modal surface for decisions that need focus, context or confirmation.', DialogPreview, snippet('Dialog', '<Dialog title="Delete draft" trigger="Delete draft">{children}</Dialog>'), rows(['title / description', 'string / string?', 'Modal heading and context.'], ['trigger', 'string', 'Button label that opens the dialog.'], ['tone', 'neutral | warning | confirmation', 'Semantic heading treatment.'], ['open / onOpenChange', 'boolean? / callback?', 'Controlled visibility.']), ['Keep the primary decision visible and provide a clear way to cancel.']),
  common('drawer', 'Drawer', 'Overlays', 'A modal surface that enters from the edge for secondary navigation or details.', DrawerPreview, snippet('Drawer', '<Drawer title="Documentation" trigger="Open drawer">{children}</Drawer>'), rows(['title / description', 'string / string?', 'Drawer heading and context.'], ['trigger', 'string', 'Button label that opens the drawer.'], ['open / onOpenChange', 'boolean? / callback?', 'Controlled visibility.']), ['Use Drawer for supporting content on small screens; keep the primary task visible behind it.']),
  common('popover', 'Popover', 'Overlays', 'A positioned surface for contextual content or a small set of controls.', PopoverPreview, snippet('Popover', '<Popover label="More information">{children}</Popover>'), rows(['label / children', 'string / ReactNode', 'Trigger label and positioned content.'], ['variant', 'default | field', 'Button or field-like trigger.'], ['open / onOpenChange', 'boolean? / callback?', 'Controlled visibility.'], ['disabled', 'boolean?', 'Prevents opening.']), ['Keep content concise and make the trigger explain what will appear.']),
]

export const componentPageMap = new Map(componentPages.map(page => [page.id, page]))

export function ComponentInstallation({ page }: { page?: Pick<ComponentSpec, 'id' | 'title' | 'source'> }) {
  const [manager, setManager] = useState('npm')
  const command = manager === 'pnpm' ? 'pnpm add' : manager === 'yarn' ? 'yarn add' : 'npm install'
  if (!page) return <Panel title="Installation workflow" description="Build, install and provide the shared foundation in one workflow." variant="split" density="compact" className="docs-installation-group">
    <Stack gap={0}>
      <CodeExample className="docs-installation-step" title="1. Build and pack the library" filename="terminal · design-system repository" source={'npm run build:atomic-library\nnpm pack ./dist-atomic-library'} />
      <CodeExample className="docs-installation-step" title="2. Install the local package" description="Use the filename printed by npm pack in your consuming application." filename="terminal · consuming application" source={`${command} ./vendor/brutalist-design-system-0.1.0-atomic.0.tgz`} controls={<Tabs label="Package manager" size="compact" value={manager} onChange={setManager} options={[{ value: 'npm', label: 'npm' }, { value: 'pnpm', label: 'pnpm' }, { value: 'yarn', label: 'yarn' }]} />} />
      <CodeExample className="docs-installation-step" title="3. Provide the shared foundation" description="Import the stylesheet once and wrap the application with AtomsRoot." filename="App.tsx" source={"import { AtomsRoot } from 'brutalist-design-system'\nimport 'brutalist-design-system/styles.css'\n\nexport default function App() {\n  return <AtomsRoot>Your application</AtomsRoot>\n}"} />
    </Stack>
  </Panel>
  return <Stack gap={6} className="docs-component-installation">
    <CodeExample headingLevel={3} title="1. Install the shared package" description="Install the package that provides the shared design-system foundation and this component." filename="terminal · consuming application" source={`${command} ./vendor/brutalist-design-system-0.1.0-atomic.0.tgz`} controls={<Tabs label="Package manager" size="compact" value={manager} onChange={setManager} options={[{ value: 'npm', label: 'npm' }, { value: 'pnpm', label: 'pnpm' }, { value: 'yarn', label: 'yarn' }]} />} />
    <CodeExample headingLevel={3} title={`2. Add ${page.title} to your application`} description={`Import ${page.title} from the public package and use it in your application.`} filename={`${page.id}.tsx`} source={page.source} />
  </Stack>
}
