export type ComponentAvailability = 'available' | 'partial' | 'missing'
export type ComponentFamily = { label: string; id: string; availability: ComponentAvailability; href?: string; aliases?: readonly string[] }
export type ComponentGroup = { title: string; items: readonly ComponentFamily[] }
const family = (label: string, id: string, availability: ComponentAvailability, aliases: readonly string[] = []): ComponentFamily => ({ label, id, availability, aliases, ...(availability === 'missing' ? {} : { href: `/page-21.html?component=${id}` }) })
/** AlignUI's component taxonomy, mapped to our existing exports where they exist. */
export const componentGroups: readonly ComponentGroup[] = [
  { title: 'Actions', items: [family('Button', 'button', 'available'), family('Feedback Button', 'feedback-button', 'available'), family('Button Group', 'button-group', 'available'), family('Compact Button', 'compact-button', 'available'), family('Fancy Button', 'fancy-button', 'available'), family('Link Button', 'text-action', 'available', ['link-button'])] },
  { title: 'Displaying Data', items: [family('Avatar', 'avatar', 'available'), family('Avatar Group', 'avatar-group', 'available'), family('Avatar Group Compact', 'avatar-group-compact', 'available'), family('Badge', 'badge', 'available', ['status-badge']), family('Banner', 'banner', 'available'), family('Data Table', 'table', 'available', ['data-table']), family('Divider', 'divider', 'available'), family('Keyboard Shortcut', 'kbd', 'available', ['kbd']), family('Progress Bar', 'progress-bar', 'available'), family('Progress Circle', 'progress-ring', 'available', ['progress-circle']), family('Rating', 'rating', 'available'), family('Tag', 'tag', 'available')] },
  { title: 'Feedback', items: [family('Alert', 'alert', 'available'), family('Notification', 'notification', 'available'), family('Toast', 'toast', 'available'), family('Tooltip', 'tooltip', 'available')] },
  { title: 'Form', items: [family('Checkbox', 'checkbox', 'available'), family('Color Picker', 'color-picker', 'available'), family('Datepicker', 'date-picker', 'partial', ['datepicker']), family('Digit Input', 'digit-input', 'available'), family('File Upload', 'file-dropzone', 'partial', ['file-upload', 'file-list', 'attachment-area']), family('Hint', 'hint', 'available'), family('Input', 'text-field', 'partial', ['search-field', 'password-field', 'number-stepper']), family('Label', 'label', 'available'), family('Radio', 'radio-group', 'available'), family('Select', 'dropdowns', 'partial', ['select', 'combobox', 'multi-select']), family('Slider', 'slider', 'partial', ['range-slider']), family('Switch', 'toggle', 'available', ['switch']), family('Textarea', 'textarea', 'available'), family('Inline text editing', 'inline-text', 'available', ['inline-editing'])] },
  { title: 'Layout', items: [family('Accordion', 'accordion', 'available'), family('Breadcrumb', 'breadcrumbs', 'available', ['breadcrumb']), family('Segmented Control', 'segmented-control', 'available'), family('Tab Menu Horizontal', 'tabs', 'partial', ['tab-menu-horizontal']), family('Tab Menu Vertical', 'tab-menu-vertical', 'available')] },
  { title: 'Navigation', items: [family('Dot Stepper', 'dot-stepper', 'available'), family('Horizontal Stepper', 'workflow-steps', 'partial', ['horizontal-stepper']), family('Pagination', 'pagination', 'available'), family('Vertical Stepper', 'vertical-stepper', 'available', ['vertical-stepper'])] },
  { title: 'Overlays', items: [family('Command Menu', 'command-menu', 'available'), family('Drawer', 'drawer', 'available'), family('Dropdown', 'menu', 'available', ['dropdown']), family('Modal', 'dialog', 'available', ['modal']), family('Popover', 'popover', 'available')] },
].map(group => ({ ...group, items: [...group.items].sort((a, b) => a.label.localeCompare(b.label, undefined, { sensitivity: 'base' })) }))
export const componentFamilyCount = componentGroups.reduce((count, group) => count + group.items.length, 0)
export const missingComponentCount = (group: ComponentGroup) => group.items.filter(item => item.availability === 'missing').length
