/** One inventory for public Component names and catalog destinations. Tests enforce parity. */
export const componentManifest = [
  { name: 'NavigationList', id: 'component-navigation-list', title: 'Navigation list' },
  { name: 'AttachmentArea', id: 'component-attachment-area', title: 'Attachment area' },
  { name: 'Button', id: 'component-button', title: 'Button' },
  { name: 'Panel', id: 'component-panel', title: 'Panel' },
  { name: 'TextField', id: 'component-text-field', title: 'Text field' },
  { name: 'Checkbox', id: 'component-checkbox', title: 'Checkbox' },
  { name: 'RadioGroup', id: 'component-radio-group', title: 'Radio group' },
  { name: 'Toggle', id: 'component-toggle', title: 'Toggle' },
  { name: 'TextArea', id: 'component-textarea', title: 'Text area' },
  { name: 'Select', id: 'component-dropdowns', title: 'Dropdowns' },
  { name: 'Tag', id: 'component-tag', title: 'Tag' },
  { name: 'SegmentedControl', id: 'component-tabs', title: 'Tabs', aliasOf: 'Tabs' },
  { name: 'Breadcrumbs', id: 'component-breadcrumbs', title: 'Breadcrumbs' },
  { name: 'Pagination', id: 'component-pagination', title: 'Pagination' },
  { name: 'NumberStepper', id: 'component-number-stepper', title: 'Number stepper' },
  { name: 'Slider', id: 'component-slider', title: 'Slider' },
  { name: 'RangeSlider', id: 'component-range-slider', title: 'Range slider' },
  { name: 'Rating', id: 'component-rating', title: 'Rating' },
  { name: 'ProgressBar', id: 'component-progress-bar', title: 'Progress bar' },
  { name: 'ProgressRing', id: 'component-progress-ring', title: 'Progress ring' },
  { name: 'StatusBadge', id: 'component-tag', title: 'Tag', aliasOf: 'Tag' },
  { name: 'Alert', id: 'component-alert', title: 'Alert' },
  { name: 'InlineText', id: 'component-inline-text', title: 'Text with inline editing' },
  { name: 'TextAction', id: 'component-text-action', title: 'Text action' },
  { name: 'Form', id: 'component-form', title: 'Form' },
  { name: 'FormActions', id: 'component-form-actions', title: 'Form actions' },
  { name: 'SearchField', id: 'component-search-field', title: 'Search field' },
  { name: 'PasswordField', id: 'component-password-field', title: 'Password field' },
  { name: 'DatePicker', id: 'component-date-picker', title: 'Date picker' },
  { name: 'Menu', id: 'component-menu', title: 'Menu' },
  { name: 'Dialog', id: 'component-dialog', title: 'Dialog' },
  { name: 'Drawer', id: 'component-drawer', title: 'Drawer' },
  { name: 'Popover', id: 'component-popover', title: 'Popover' },
  { name: 'Tooltip', id: 'component-tooltip', title: 'Tooltip' },
  { name: 'Toast', id: 'component-toast', title: 'Toast' },
  { name: 'Tabs', id: 'component-tabs', title: 'Tabs' },
  { name: 'WorkflowSteps', id: 'component-workflow-steps', title: 'Workflow steps' },
  { name: 'Table', id: 'component-table', title: 'Table' },
  { name: 'Combobox', id: 'component-dropdowns', title: 'Dropdowns', groupedWith: 'Select' },
  { name: 'MultiSelect', id: 'component-dropdowns', title: 'Dropdowns', groupedWith: 'Select' },
  { name: 'InlineConfirmation', id: 'component-inline-confirmation', title: 'Inline confirmation' },
  { name: 'FileDropzone', id: 'component-file-dropzone', title: 'File dropzone' },
  { name: 'FileList', id: 'component-file-list', title: 'File list' },
  { name: 'EmptyState', id: 'component-empty-state', title: 'Empty state' },
  { name: 'Spinner', id: 'component-spinner', title: 'Spinner' },
  { name: 'Skeleton', id: 'component-skeleton', title: 'Skeleton' },
]
